/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fc.AfficherListePatientsListener;
import fc.DialogueBD;
import fc.Utilisateur;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Objects;

/**
 *
 * @author Antoine
 */
public class Accueil extends javax.swing.JFrame implements AfficherListePatientsListener {

    /**
     * Creates new form Accueil2
     */

    // L'attribut longueur correspond à la longueur de l'écran


    //Code couleur : bleu foncé -> 044272
    //Code couleur : bleu clair -> ecf2fe
    private final DialogueBD dialogueBD;
    private final Utilisateur utilisateur;
    private AfficherListePatients scrollPaneTable;
    public Accueil(DialogueBD dialogueBD, Utilisateur utilisateur) {
//On récupère la taille de l'écran
        Dimension tailleMoniteur = Toolkit.getDefaultToolkit().getScreenSize();
        //On stocke la largeur de l'écran dans la variable largeur

        initComponents();
        //Le panneau Ouest prend pour dimension longueur1 et hauteur

        this.dialogueBD = dialogueBD;
        // On affiche le nom de l'utilisateur en Titre de la JFrame
        this.utilisateur = utilisateur;
        this.setTitle("Bienvenue " + utilisateur.getPrenom().trim() + " " + utilisateur.getNom().trim());
        // On met la JFrame en plein écran
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon iconeSmartiz = new ImageIcon(getClass().getResource("/ui/Image/Logo_Smartiz.png"));
        Image imageSmartiz = iconeSmartiz.getImage();
        Image scaledImage = imageSmartiz.getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), Image.SCALE_SMOOTH);
        labelLogo.setIcon(new ImageIcon(scaledImage));
        changerLangue(this.utilisateur.getLangue());
    }

    public void changerLangue(String langue) {
        if (langue.equals("English")) {
            BoutonMedecins.setText("Physicians");
            Deconnexion.setText("Disconnection");
            BoutonServices.setText("Medical Services");
            BoutonRechercheClinique.setText("Clinical trial");
            RechercherUnPatient.setText("Search for a patient");
            BoutonRechercher.setText("Search");
            Nom.setText("Last name");
            Prenom.setText("First name");
            DateDeNaissance.setText("Date of birth");
            Bienvenue.setText("Welcome");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauOuest = new javax.swing.JPanel();
        BoutonMedecins = new javax.swing.JButton();
        Deconnexion = new javax.swing.JButton();
        BoutonServices = new javax.swing.JButton();
        BoutonPatients = new javax.swing.JButton();
        BoutonRechercheClinique = new javax.swing.JButton();
        PanneauNord = new javax.swing.JPanel();
        PanneauRecherche = new javax.swing.JPanel();
        RechercherUnPatient = new javax.swing.JLabel();
        texteIPP = new javax.swing.JTextField();
        BoutonRechercher = new javax.swing.JButton();
        IPP = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        texteNom = new javax.swing.JTextField();
        Prenom = new javax.swing.JLabel();
        textePrenom = new javax.swing.JTextField();
        DateDeNaissance = new javax.swing.JLabel();
        texteDateNaissance = new javax.swing.JTextField();
        PanneauLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        PanneauPrincipale = new javax.swing.JPanel();
        PanneauPrincipaleNord = new javax.swing.JPanel();
        PanneauPrincipalOuest = new javax.swing.JPanel();
        PanneauPrincipaleEst = new javax.swing.JPanel();
        PanneauPrincipaleSud = new javax.swing.JPanel();
        PanneauPrincipaleCentral = new javax.swing.JPanel();
        Bienvenue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 242, 254));

        PanneauOuest.setBackground(new java.awt.Color(236, 242, 254));

        BoutonMedecins.setBackground(new java.awt.Color(4, 66, 114));
        BoutonMedecins.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BoutonMedecins.setForeground(new java.awt.Color(255, 255, 255));
        BoutonMedecins.setText("Médecins");

        Deconnexion.setBackground(new java.awt.Color(4, 66, 114));
        Deconnexion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setText("Déconnexion");

        BoutonServices.setBackground(new java.awt.Color(4, 66, 114));
        BoutonServices.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BoutonServices.setForeground(new java.awt.Color(255, 255, 255));
        BoutonServices.setText("Services");

        BoutonPatients.setBackground(new java.awt.Color(4, 66, 114));
        BoutonPatients.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BoutonPatients.setForeground(new java.awt.Color(255, 255, 255));
        BoutonPatients.setText("Patients");
        BoutonPatients.setToolTipText("");
        BoutonPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonPatientsActionPerformed(evt);
            }
        });

        BoutonRechercheClinique.setBackground(new java.awt.Color(4, 66, 114));
        BoutonRechercheClinique.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BoutonRechercheClinique.setForeground(new java.awt.Color(255, 255, 255));
        BoutonRechercheClinique.setText("Recherche Clinique");
        BoutonRechercheClinique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRechercheCliniqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanneauOuestLayout = new javax.swing.GroupLayout(PanneauOuest);
        PanneauOuest.setLayout(PanneauOuestLayout);
        PanneauOuestLayout.setHorizontalGroup(
            PanneauOuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauOuestLayout.createSequentialGroup()
                .addGroup(PanneauOuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonServices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoutonMedecins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoutonPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Deconnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauOuestLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BoutonRechercheClinique, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanneauOuestLayout.setVerticalGroup(
            PanneauOuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauOuestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonServices, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoutonMedecins, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoutonPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoutonRechercheClinique, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(Deconnexion)
                .addContainerGap())
        );

        getContentPane().add(PanneauOuest, java.awt.BorderLayout.WEST);

        PanneauNord.setBackground(new java.awt.Color(255, 255, 255));
        PanneauNord.setLayout(new java.awt.BorderLayout());

        PanneauRecherche.setBackground(new java.awt.Color(236, 242, 254));

        RechercherUnPatient.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RechercherUnPatient.setText(" Rechercher un patient :");
        RechercherUnPatient.setPreferredSize(new Dimension(400,75));

        texteIPP.setName("idPatient"); // NOI18N

        BoutonRechercher.setBackground(new java.awt.Color(4, 66, 114));
        BoutonRechercher.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonRechercher.setForeground(new java.awt.Color(255, 255, 255));
        BoutonRechercher.setText("Rechercher");
        BoutonRechercher.setPreferredSize(new java.awt.Dimension(97, 40));
        BoutonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRechercherActionPerformed(evt);
            }
        });

        IPP.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        IPP.setText("IPP");

        Nom.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Nom.setText("Nom ");

        texteNom.setName("nom"); // NOI18N
        texteNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteNomActionPerformed(evt);
            }
        });

        Prenom.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Prenom.setText("Prénom");

        textePrenom.setName("prenom"); // NOI18N

        DateDeNaissance.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DateDeNaissance.setText("Date de Naissance");

        texteDateNaissance.setName("dateNaissance"); // NOI18N

        PanneauLogo.setBackground(new java.awt.Color(236, 242, 254));

        labelLogo.setBackground(new java.awt.Color(236, 242, 254));

        javax.swing.GroupLayout PanneauLogoLayout = new javax.swing.GroupLayout(PanneauLogo);
        PanneauLogo.setLayout(PanneauLogoLayout);
        PanneauLogoLayout.setHorizontalGroup(
            PanneauLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauLogoLayout.createSequentialGroup()
                .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanneauLogoLayout.setVerticalGroup(
            PanneauLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauLogoLayout.createSequentialGroup()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanneauRechercheLayout = new javax.swing.GroupLayout(PanneauRecherche);
        PanneauRecherche.setLayout(PanneauRechercheLayout);
        PanneauRechercheLayout.setHorizontalGroup(
            PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanneauLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauRechercheLayout.createSequentialGroup()
                        .addComponent(DateDeNaissance)
                        .addGap(18, 18, 18)
                        .addComponent(texteDateNaissance))
                    .addGroup(PanneauRechercheLayout.createSequentialGroup()
                        .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanneauRechercheLayout.createSequentialGroup()
                                .addComponent(Nom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texteNom, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Prenom))
                            .addGroup(PanneauRechercheLayout.createSequentialGroup()
                                .addComponent(RechercherUnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(IPP)))
                        .addGap(18, 18, 18)
                        .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texteIPP, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                            .addComponent(textePrenom))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoutonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        PanneauRechercheLayout.setVerticalGroup(
            PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauRechercheLayout.createSequentialGroup()
                        .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RechercherUnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texteIPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoutonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IPP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Prenom))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Nom)
                                .addComponent(texteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateDeNaissance)
                            .addComponent(texteDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanneauLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanneauNord.add(PanneauRecherche, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanneauNord, java.awt.BorderLayout.NORTH);

        PanneauPrincipale.setBackground(new java.awt.Color(236, 242, 254));
        PanneauPrincipale.setLayout(new java.awt.BorderLayout());

        PanneauPrincipaleNord.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanneauPrincipaleNordLayout = new javax.swing.GroupLayout(PanneauPrincipaleNord);
        PanneauPrincipaleNord.setLayout(PanneauPrincipaleNordLayout);
        PanneauPrincipaleNordLayout.setHorizontalGroup(
            PanneauPrincipaleNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PanneauPrincipaleNordLayout.setVerticalGroup(
            PanneauPrincipaleNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanneauPrincipale.add(PanneauPrincipaleNord, java.awt.BorderLayout.PAGE_START);

        PanneauPrincipalOuest.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanneauPrincipalOuestLayout = new javax.swing.GroupLayout(PanneauPrincipalOuest);
        PanneauPrincipalOuest.setLayout(PanneauPrincipalOuestLayout);
        PanneauPrincipalOuestLayout.setHorizontalGroup(
            PanneauPrincipalOuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanneauPrincipalOuestLayout.setVerticalGroup(
            PanneauPrincipalOuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        PanneauPrincipale.add(PanneauPrincipalOuest, java.awt.BorderLayout.LINE_START);

        PanneauPrincipaleEst.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanneauPrincipaleEstLayout = new javax.swing.GroupLayout(PanneauPrincipaleEst);
        PanneauPrincipaleEst.setLayout(PanneauPrincipaleEstLayout);
        PanneauPrincipaleEstLayout.setHorizontalGroup(
            PanneauPrincipaleEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanneauPrincipaleEstLayout.setVerticalGroup(
            PanneauPrincipaleEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        PanneauPrincipale.add(PanneauPrincipaleEst, java.awt.BorderLayout.LINE_END);

        PanneauPrincipaleSud.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanneauPrincipaleSudLayout = new javax.swing.GroupLayout(PanneauPrincipaleSud);
        PanneauPrincipaleSud.setLayout(PanneauPrincipaleSudLayout);
        PanneauPrincipaleSudLayout.setHorizontalGroup(
            PanneauPrincipaleSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PanneauPrincipaleSudLayout.setVerticalGroup(
            PanneauPrincipaleSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanneauPrincipale.add(PanneauPrincipaleSud, java.awt.BorderLayout.PAGE_END);

        PanneauPrincipaleCentral.setBackground(new java.awt.Color(255, 255, 255));
        PanneauPrincipaleCentral.setLayout(new java.awt.BorderLayout());

        Bienvenue.setFont(new java.awt.Font("Segoe Script", 0, 80)); // NOI18N
        Bienvenue.setForeground(new java.awt.Color(4, 66, 114));
        Bienvenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenue.setText("Bienvenue");
        PanneauPrincipaleCentral.add(Bienvenue, java.awt.BorderLayout.NORTH);

        PanneauPrincipale.add(PanneauPrincipaleCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanneauPrincipale, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRechercherActionPerformed
        // -------------------- On récupère la liste des patients qui correspondent à la recherche ---------------------
        // On récupère les champs de la recherche dans une HashMap
        HashMap<String, String> dataPatient = new HashMap<>();
        // Pour chaque component, on vérifie si c'est un JTextField, si c'est le cas, on ajoute le contenu du JTextField dans la HashMap
        for (Component component : PanneauRecherche.getComponents()) {
            if (component instanceof JTextField) {
                JTextField textField = (JTextField) component;
                if (!textField.getText().isEmpty()) { // On vérifie que le JTextField ne soit pas vide
                    dataPatient.put(textField.getName(), textField.getText());
                }
            }
        }
        if(utilisateur.isPersonnelMedical()) {
            // On ne veut que les patients du service de l'utilisateur
            dataPatient.put("idService", Integer.toString(utilisateur.getIdService()));
        }
        //On récupère les patients qui correspondent à la recherche
        ResultSet resultSetPatients = dialogueBD.getPatients(dataPatient);

        this.scrollPaneTable = new AfficherListePatients(resultSetPatients);
        this.scrollPaneTable.addPatientSelectedListener(this);

        // ---------------- On affiche la liste des patients qui correspondent à la recherche -----------------------
        //On supprime tous les composants du panneau principal
        for (Component component : PanneauPrincipale.getComponents()) {
            PanneauPrincipale.remove(component);
        }
        //On ajoute le JScrollPane au panneau principal
        PanneauPrincipale.add(scrollPaneTable, java.awt.BorderLayout.CENTER);
        //On actualise le panneau principal
        PanneauPrincipale.revalidate();
    }//GEN-LAST:event_BoutonRechercherActionPerformed

    private void texteNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteNomActionPerformed

    private void BoutonPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonPatientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonPatientsActionPerformed

    private void BoutonRechercheCliniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRechercheCliniqueActionPerformed
        //On supprime tous les composants du panneau principal
        for (Component component : PanneauPrincipale.getComponents()) {
            PanneauPrincipale.remove(component);
        }
        //On ajoute le JScrollPane au panneau principal
        PanneauPrincipale.add(new AffichageListeEtude(dialogueBD,utilisateur), java.awt.BorderLayout.CENTER);
        //On actualise le panneau principal
        PanneauPrincipale.revalidate();
    }//GEN-LAST:event_BoutonRechercheCliniqueActionPerformed

    public void patientSelected(String idPatient) {
        // On crée un nouveau panel pour afficher les informations du patient
        AffichagePatient affichagePatient = new AffichagePatient(idPatient, utilisateur, dialogueBD);
        // On enlève le panel actuel du panneau principal central
        PanneauPrincipale.remove(scrollPaneTable);
        // On ajoute le nouveau panel au panneau principal central
        PanneauPrincipale.add(affichagePatient, BorderLayout.CENTER);
        // On actualise le panneau principal central
        PanneauPrincipale.revalidate();
        PanneauPrincipale.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            final Utilisateur utilisateur = new Utilisateur("Cot", "Harry", true, "Français", 1, 1111, "Y");
            final DialogueBD dialogueBD = new DialogueBD();
            {
                dialogueBD.connect();
            }
            public void run() {
                new Accueil(dialogueBD, utilisateur).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenue;
    private javax.swing.JButton BoutonMedecins;
    private javax.swing.JButton BoutonPatients;
    private javax.swing.JButton BoutonRechercheClinique;
    private javax.swing.JButton BoutonRechercher;
    private javax.swing.JButton BoutonServices;
    private javax.swing.JLabel DateDeNaissance;
    private javax.swing.JButton Deconnexion;
    private javax.swing.JLabel IPP;
    private javax.swing.JLabel Nom;
    private javax.swing.JPanel PanneauLogo;
    private javax.swing.JPanel PanneauNord;
    private javax.swing.JPanel PanneauOuest;
    private javax.swing.JPanel PanneauPrincipalOuest;
    private javax.swing.JPanel PanneauPrincipale;
    private javax.swing.JPanel PanneauPrincipaleCentral;
    private javax.swing.JPanel PanneauPrincipaleEst;
    private javax.swing.JPanel PanneauPrincipaleNord;
    private javax.swing.JPanel PanneauPrincipaleSud;
    private javax.swing.JPanel PanneauRecherche;
    private javax.swing.JLabel Prenom;
    private javax.swing.JLabel RechercherUnPatient;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JTextField texteDateNaissance;
    private javax.swing.JTextField texteIPP;
    private javax.swing.JTextField texteNom;
    private javax.swing.JTextField textePrenom;
    // End of variables declaration//GEN-END:variables
}
