/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;
import java.awt.Toolkit;

import fc.DialogueBD;
import fc.Utilisateur;

/**
 *
 * @author emmaa
 */
public class AffichageListeEtude extends javax.swing.JPanel {

    /**
     * Creates new form AffichageListeEtude
     */
     // L'attribut longueur correspond à la longueur de l'écran
    protected int largeur;
    //L'attribut longueur1 correspond à la longueur du panneau Ouest de la fenêtre 
    protected int largeur1;
    // L'attribut hauteur correspond à la hauteur de l'écran
    protected int hauteur;
    //L'attribut hauteur1 correspond à la hauteur du panneau Ouest 
    protected int hauteur1;
    //L'attribut hauteur2 correspond à la hauteur du panneau Nord
    protected int hauteur2;
    //L'attribut largeurCentré correspond à 1/4 de largeur - largeur1
    protected int largeurCentree;
    //L'attribut largeurBouton correspond à la largeur des boutons d'ajout pour consultation, anesthésie, examen, prescription et radiologie
    protected int largeurBouton;
    //L'attribut hauteurInfo correspond à la hauteur du panneau info
    protected int hauteurInfo;
    //L'attribut hauteurCentral correspond à la hauteur du panneau central
    protected int hauteurCentral;

    public DialogueBD dialogueBD;
    public Utilisateur utilisateur;
    
    public AffichageListeEtude(DialogueBD dialogueBD, Utilisateur utilisateur) {
         //On récupère la taille de l'écran
        Dimension tailleMoniteur = Toolkit.getDefaultToolkit().getScreenSize();
        //On stocke la largeur de l'écran dans la variable largeur
        largeur = tailleMoniteur.width;
        //On stocke la hauteur de l'écran dans la variable hauteur
        hauteur = tailleMoniteur.height;
        //L'attribut largeur1 correspond à 1/5 de la largeur de l'écran
        largeur1 = largeur / 5;
        //L'attribut largeurCentré correspond à 1/4 de (largeur-largeur1)
        largeurCentree = (largeur - largeur1) / 4;
        //L'attribut hauteur1 correspond à 4/5 de la hauteur de l'écran
        hauteur1 = hauteur - hauteur2;
        //L'attribut hauteur 2 correspond à 1/5 de la hauteur de l'écran
        hauteur2 = hauteur / 5;
        //L'attribut largeurBouton correspond à 1/8 de la largeur de largeurCentree
        largeurBouton = largeurCentree / 8;
        hauteurInfo = 1;
        initComponents();
        //On stocke les données de l'utilisateur et la connexion à la BD
        this.dialogueBD = dialogueBD;
        this.utilisateur = utilisateur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauNord = new javax.swing.JPanel();
        ListeEtudeClinique = new javax.swing.JLabel();
        BoutonCreerEtude = new javax.swing.JButton();
        PanneauSud = new javax.swing.JPanel();
        PanneauCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeEtude = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new Dimension(largeur-largeur1,hauteur1));
        setLayout(new java.awt.BorderLayout());

        PanneauNord.setBackground(new java.awt.Color(255, 255, 255));
        PanneauNord.setPreferredSize(new java.awt.Dimension(750, 80));

        ListeEtudeClinique.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ListeEtudeClinique.setForeground(new java.awt.Color(4, 66, 114));
        ListeEtudeClinique.setText("Liste des études cliniques");

        BoutonCreerEtude.setBackground(new java.awt.Color(255, 255, 255));
        BoutonCreerEtude.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        BoutonCreerEtude.setForeground(new java.awt.Color(4, 66, 114));
        BoutonCreerEtude.setText("Créer une étude");
        BoutonCreerEtude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonCreerEtudeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanneauNordLayout = new javax.swing.GroupLayout(PanneauNord);
        PanneauNord.setLayout(PanneauNordLayout);
        PanneauNordLayout.setHorizontalGroup(
            PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauNordLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonCreerEtude)
                    .addComponent(ListeEtudeClinique))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        PanneauNordLayout.setVerticalGroup(
            PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauNordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListeEtudeClinique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoutonCreerEtude)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(PanneauNord, java.awt.BorderLayout.PAGE_START);

        PanneauSud.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanneauSudLayout = new javax.swing.GroupLayout(PanneauSud);
        PanneauSud.setLayout(PanneauSudLayout);
        PanneauSudLayout.setHorizontalGroup(
            PanneauSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanneauSudLayout.setVerticalGroup(
            PanneauSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(PanneauSud, java.awt.BorderLayout.PAGE_END);

        PanneauCentre.setBackground(new java.awt.Color(255, 255, 255));
        PanneauCentre.setLayout(new java.awt.BorderLayout());

        ListeEtude.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListeEtude);

        PanneauCentre.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(PanneauCentre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonCreerEtudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonCreerEtudeActionPerformed
        //On ouvre le formulaire pour créer une étude 
        AjouterEtude ajoutEtude = new AjouterEtude(dialogueBD,utilisateur.getLangue());
        ajoutEtude.setVisible(true);
    }//GEN-LAST:event_BoutonCreerEtudeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonCreerEtude;
    private javax.swing.JList ListeEtude;
    private javax.swing.JLabel ListeEtudeClinique;
    private javax.swing.JPanel PanneauCentre;
    private javax.swing.JPanel PanneauNord;
    private javax.swing.JPanel PanneauSud;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
