/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fc.DialogueBD;
import fc.Utilisateur;

import javax.swing.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Objects;

/**
 * @author emmaa
 */
public class AffichagePatient extends javax.swing.JPanel {

    /**
     * Creates new form AffichagePatient
     */
    // L'attribut longueur correspond à la longueur de l'écran
    protected int largeur;
    //L'attribut longueur1 correspond à la longueur du panneau Ouest
    protected int largeur1;
    // L'attribut hauteur correspond à la hauteur de l'écran
    protected int hauteur;
    //L'attribut hauteur1 correspond à la hauteur du panneau Ouest 
    protected int hauteur1;
    //L'attribut hauteur2 correspond à la hauteur du panneau Nord
    protected int hauteur2;
    //L'attribut largeurCentré correspond à 1/4 de largeur - largeur1
    protected int largeurCentree;
    //L'attribut largeurBouton correspond à la largeur des boutons d'ajout pour consultation, anesthésie, examen, prescription et radiologie
    protected int largeurBouton;
    //L'attribut hauteurInfo correspond à la hauteur du panneau info
    protected int hauteurInfo;
    //L'attribut hauteurCentral correspond à la hauteur du panneau central
    protected int hauteurCentral;

    //Code couleur : bleu foncé -> 044272
    //Code couleur : bleu clair -> ecf2fe

    public DialogueBD dialogueBD;
    public Utilisateur utilisateur;

    public AffichagePatient(String idPatient, Utilisateur utilisateur, DialogueBD dialogueBD) {

        //-------- On définit les dimensions du panneau et de ses composants en fonction de la taille de l'écran -------
        //On récupère la taille de l'écran
        Dimension tailleMoniteur = Toolkit.getDefaultToolkit().getScreenSize();
        //On stocke la largeur de l'écran dans la variable largeur
        largeur = tailleMoniteur.width;
        //On stocke la hauteur de l'écran dans la variable hauteur
        hauteur = tailleMoniteur.height;
        //L'attribut largeur1 correspond à 1/5 de la largeur de l'écran
        largeur1 = largeur / 5;
        //L'attribut largeurCentré correspond à 1/4 de (largeur-largeur1)
        largeurCentree = (largeur - largeur1) / 4;
        //L'attribut hauteur1 correspond à 4/5 de la hauteur de l'écran
        hauteur1 = hauteur - hauteur2;
        //L'attribut hauteur 2 correspond à 1/5 de la hauteur de l'écran
        hauteur2 = hauteur / 5;
        //L'attribut largeurBouton correspond à 1/8 de la largeur de largeurCentree
        largeurBouton = largeurCentree / 8;
        hauteurInfo = 1;

        // -------------------------------- On initialise les composants de l'interface --------------------------------
        initComponents();
        //On définit le texte du label nomUtilisateur
        this.utilisateur = utilisateur;
        this.nomUtilisateur.setText(utilisateur.getPrenom().trim() + " " + utilisateur.getNom().trim());
        this.dialogueBD = dialogueBD;
        // On remplit les informations du patient
        remplirChampsPatient(idPatient);
        remplirSejours(idPatient);
        remplirActes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        PanneauNord = new javax.swing.JPanel();
        NomPrenomPatient = new javax.swing.JLabel();
        NeeLe = new javax.swing.JLabel();
        DateNaissancePatient = new javax.swing.JLabel();
        Sexe = new javax.swing.JLabel();
        SexePatient = new javax.swing.JLabel();
        IPPPatient = new javax.swing.JLabel();
        Adresse = new javax.swing.JLabel();
        AdressePatient = new javax.swing.JLabel();
        Telephone = new javax.swing.JLabel();
        TelephonePatient = new javax.swing.JLabel();
        Fumeur = new javax.swing.JLabel();
        FumeurPatient = new javax.swing.JLabel();
        Alcool = new javax.swing.JLabel();
        AlcoolPatient = new javax.swing.JLabel();
        PanneauSud = new javax.swing.JPanel();
        panelCloture = new javax.swing.JPanel();
        boutonCloture = new javax.swing.JButton();
        nomUtilisateur = new javax.swing.JLabel();
        PanneauCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        panelSejourEtBoutons = new javax.swing.JPanel();
        MenuDeroulantSejours = new javax.swing.JComboBox();
        Ajout = new javax.swing.JLabel();
        PanelBoutons = new javax.swing.JPanel();
        BoutonRadiologie = new javax.swing.JButton();
        BoutonAnesthesie = new javax.swing.JButton();
        BoutonConsultation = new javax.swing.JButton();
        BoutonPrescription = new javax.swing.JButton();
        BoutonExamenBiologique = new javax.swing.JButton();

        setPreferredSize(new Dimension(largeur-largeur1,hauteur1));
        setLayout(new java.awt.BorderLayout());

        PanneauNord.setBackground(new java.awt.Color(255, 255, 255));
        PanneauNord.setPreferredSize(new java.awt.Dimension(707, 150));

        NomPrenomPatient.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        NomPrenomPatient.setForeground(new java.awt.Color(4, 66, 114));
        NomPrenomPatient.setText("NomPrenomPatient");

        NeeLe.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        NeeLe.setForeground(new java.awt.Color(4, 66, 114));
        NeeLe.setText("Né(e) le : ");

        DateNaissancePatient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        DateNaissancePatient.setText("DateNaissancePatient");

        Sexe.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Sexe.setForeground(new java.awt.Color(4, 66, 114));
        Sexe.setText("Sexe : ");

        SexePatient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        SexePatient.setText("SexePatient");

        IPPPatient.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        IPPPatient.setText("IPPPatient");

        Adresse.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Adresse.setForeground(new java.awt.Color(4, 66, 114));
        Adresse.setText("Adresse : ");

        AdressePatient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AdressePatient.setText("AdressePatient");

        Telephone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Telephone.setForeground(new java.awt.Color(4, 66, 114));
        Telephone.setText("Téléphone : ");

        TelephonePatient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TelephonePatient.setText("TelephonePatient");

        Fumeur.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Fumeur.setForeground(new java.awt.Color(4, 66, 114));
        Fumeur.setText("Fumeur : ");

        FumeurPatient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        FumeurPatient.setText("FumeurPatient");

        Alcool.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Alcool.setForeground(new java.awt.Color(4, 66, 114));
        Alcool.setText("Alcool : ");

        AlcoolPatient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        AlcoolPatient.setText("AlcoolPatient");

        javax.swing.GroupLayout PanneauNordLayout = new javax.swing.GroupLayout(PanneauNord);
        PanneauNord.setLayout(PanneauNordLayout);
        PanneauNordLayout.setHorizontalGroup(
            PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauNordLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauNordLayout.createSequentialGroup()
                        .addComponent(NeeLe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateNaissancePatient)
                        .addGap(64, 64, 64)
                        .addComponent(Sexe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SexePatient)
                        .addGap(67, 67, 67)
                        .addComponent(Telephone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelephonePatient))
                    .addGroup(PanneauNordLayout.createSequentialGroup()
                        .addComponent(NomPrenomPatient)
                        .addGap(41, 41, 41)
                        .addComponent(IPPPatient))
                    .addGroup(PanneauNordLayout.createSequentialGroup()
                        .addComponent(Adresse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdressePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanneauNordLayout.createSequentialGroup()
                        .addComponent(Fumeur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FumeurPatient)
                        .addGap(109, 109, 109)
                        .addComponent(Alcool)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlcoolPatient)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanneauNordLayout.setVerticalGroup(
            PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauNordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomPrenomPatient)
                    .addComponent(IPPPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NeeLe)
                    .addComponent(DateNaissancePatient)
                    .addComponent(Sexe)
                    .addComponent(SexePatient)
                    .addComponent(Telephone)
                    .addComponent(TelephonePatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adresse)
                    .addComponent(AdressePatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fumeur)
                    .addComponent(FumeurPatient)
                    .addComponent(Alcool)
                    .addComponent(AlcoolPatient))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(PanneauNord, java.awt.BorderLayout.PAGE_START);

        PanneauSud.setBackground(new java.awt.Color(255, 255, 255));
        PanneauSud.setPreferredSize(new java.awt.Dimension(707, 50));
        PanneauSud.setLayout(new java.awt.BorderLayout());

        panelCloture.setBackground(new java.awt.Color(255, 255, 255));

        boutonCloture.setBackground(new java.awt.Color(255, 255, 255));
        boutonCloture.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        boutonCloture.setForeground(new java.awt.Color(4, 66, 144));
        boutonCloture.setText("Cloturer le séjour");
        boutonCloture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonClotureActionPerformed(evt);
            }
        });

        nomUtilisateur.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        nomUtilisateur.setText("nomUtilisateur \n");

        javax.swing.GroupLayout panelClotureLayout = new javax.swing.GroupLayout(panelCloture);
        panelCloture.setLayout(panelClotureLayout);
        panelClotureLayout.setHorizontalGroup(
            panelClotureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClotureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                .addComponent(boutonCloture)
                .addContainerGap())
        );
        panelClotureLayout.setVerticalGroup(
            panelClotureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClotureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomUtilisateur)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(panelClotureLayout.createSequentialGroup()
                .addComponent(boutonCloture)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanneauSud.add(panelCloture, java.awt.BorderLayout.CENTER);

        add(PanneauSud, java.awt.BorderLayout.PAGE_END);

        PanneauCentral.setBackground(new java.awt.Color(255, 255, 255));
        PanneauCentral.setPreferredSize(new Dimension(largeur-largeur1,hauteur1));
        PanneauCentral.setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        PanneauCentral.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelSejourEtBoutons.setBackground(new java.awt.Color(255, 255, 255));

        MenuDeroulantSejours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeroulantSejoursActionPerformed(evt);
            }
        });

        Ajout.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Ajout.setText("Ajouter un(e) :");

        PanelBoutons.setBackground(new java.awt.Color(255, 255, 255));
        PanelBoutons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BoutonRadiologie.setBackground(new java.awt.Color(236, 242, 254));
        BoutonRadiologie.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BoutonRadiologie.setForeground(new java.awt.Color(4, 66, 114));
        BoutonRadiologie.setText("Radiologie");
        PanelBoutons.add(BoutonRadiologie);

        BoutonAnesthesie.setBackground(new java.awt.Color(236, 242, 254));
        BoutonAnesthesie.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BoutonAnesthesie.setForeground(new java.awt.Color(4, 66, 114));
        BoutonAnesthesie.setText("Anesthésie");
        PanelBoutons.add(BoutonAnesthesie);

        BoutonConsultation.setBackground(new java.awt.Color(236, 242, 254));
        BoutonConsultation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BoutonConsultation.setForeground(new java.awt.Color(4, 66, 114));
        BoutonConsultation.setText("Consultation");
        BoutonConsultation.setToolTipText("");
        BoutonConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonConsultationActionPerformed(evt);
            }
        });
        PanelBoutons.add(BoutonConsultation);

        BoutonPrescription.setBackground(new java.awt.Color(236, 242, 254));
        BoutonPrescription.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BoutonPrescription.setForeground(new java.awt.Color(4, 66, 114));
        BoutonPrescription.setText("Prescription");
        BoutonPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonPrescriptionActionPerformed(evt);
            }
        });
        PanelBoutons.add(BoutonPrescription);

        BoutonExamenBiologique.setBackground(new java.awt.Color(236, 242, 254));
        BoutonExamenBiologique.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BoutonExamenBiologique.setForeground(new java.awt.Color(4, 66, 114));
        BoutonExamenBiologique.setText("Examen Biologique");
        BoutonExamenBiologique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonExamenBiologiqueActionPerformed(evt);
            }
        });
        PanelBoutons.add(BoutonExamenBiologique);

        javax.swing.GroupLayout panelSejourEtBoutonsLayout = new javax.swing.GroupLayout(panelSejourEtBoutons);
        panelSejourEtBoutons.setLayout(panelSejourEtBoutonsLayout);
        panelSejourEtBoutonsLayout.setHorizontalGroup(
            panelSejourEtBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSejourEtBoutonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSejourEtBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelBoutons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSejourEtBoutonsLayout.createSequentialGroup()
                        .addComponent(Ajout)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MenuDeroulantSejours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSejourEtBoutonsLayout.setVerticalGroup(
            panelSejourEtBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSejourEtBoutonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuDeroulantSejours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ajout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        PanneauCentral.add(panelSejourEtBoutons, java.awt.BorderLayout.NORTH);

        add(PanneauCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonExamenBiologiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonExamenBiologiqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonExamenBiologiqueActionPerformed

    private void boutonClotureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonClotureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonClotureActionPerformed

    private void MenuDeroulantSejoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeroulantSejoursActionPerformed
        remplirActes();
    }//GEN-LAST:event_MenuDeroulantSejoursActionPerformed

    private void BoutonConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonConsultationActionPerformed
        String idSejour;
        // On récupère l'identifiant du séjour sélectionné
        if(MenuDeroulantSejours.getSelectedItem().toString().contains("Consultation")) {
            idSejour = MenuDeroulantSejours.getSelectedItem().toString().substring(15, 16);
        }else {
            idSejour = MenuDeroulantSejours.getSelectedItem().toString().substring(9, 10);
        }
        // On ouvre la fenêtre d'ajout de consultation
        JFrame AjoutConsultation = new AjoutConsultation(dialogueBD, this.utilisateur, idSejour);
        // On affiche la fenêtre
        AjoutConsultation.setVisible(true);
        // On ajoute un listener pour mettre à jour la liste des actes après l'ajout de la consultation
        AjoutConsultation.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                remplirActes();
            }
        });
    }//GEN-LAST:event_BoutonConsultationActionPerformed

    private void BoutonPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonPrescriptionActionPerformed
        String idSejour;
        // On récupère l'identifiant du séjour sélectionné
        if(MenuDeroulantSejours.getSelectedItem().toString().contains("Consultation")) {
            idSejour = MenuDeroulantSejours.getSelectedItem().toString().substring(15, 16);
        }else {
            idSejour = MenuDeroulantSejours.getSelectedItem().toString().substring(9, 10);
        }
        // On ouvre la fenêtre d'ajout de prescription
        JFrame AjoutPrescription = new AjouterPrescription(dialogueBD, this.utilisateur, idSejour);
        // On affiche la fenêtre
        AjoutPrescription.setVisible(true);
        // On ajoute un listener pour mettre à jour la liste des actes après l'ajout de la prescription
        AjoutPrescription.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                remplirActes();
            }
        });


    }//GEN-LAST:event_BoutonPrescriptionActionPerformed

    /**
     * Remplit les champs de l'interface avec les informations du patient
     *
     * @param idPatient  l'identifiant du patient à afficher
     */
    public void remplirChampsPatient(String idPatient) {
        // On récupère les informations du patient
        try {
            // On effectue une recherche dans la table Patient avec l'IPP du patient sélectionné
            ResultSet resultat = dialogueBD.rechercheTable(
                    "Patient",
                    new HashMap<String, String>() {{
                        put("idPatient", (String) idPatient);
                    }},
                    false);
            // On se positionne sur le premier (et unique) résultat
            resultat.next();
            // On remplit les champs
            NomPrenomPatient.setText(resultat.getString("nom").trim() + " " + resultat.getString("prenom").trim());
            DateNaissancePatient.setText(resultat.getString("dateNaissance").substring(0, 10));
            SexePatient.setText(resultat.getString("sexe"));
            IPPPatient.setText("IPP : " + resultat.getString("idPatient"));
            AdressePatient.setText(resultat.getString("adresse").trim()); // On enlève les espaces inutiles
            TelephonePatient.setText(resultat.getString("telephone"));
            FumeurPatient.setText(Objects.equals(resultat.getString("fumeur"), "Y") ? "Oui" : "Non");
            AlcoolPatient.setText(Objects.equals(resultat.getString("alcool"), "Y") ? "Oui" : "Non");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Remplit le menu déroulant des séjours du patient
     *
     * @param idPatient  l'identifiant du patient sélectionné
     */
    public void remplirSejours(String idPatient) {
        // On récupère les séjours du patient

        // On effectue une recherche dans la table Sejour avec l'IPP du patient sélectionné
        try (ResultSet resultat = dialogueBD.rechercheTable(
                "Sejour",
                new HashMap<String, String>() {{
                    put("idPatient", (String) idPatient);
                }},
                false)) {

            // On ajoute chaque séjour du patient dans le menu déroulant
            while (resultat.next()) {
                // On construit le texte à afficher dans le menu déroulant
                // Si le séjour est une consultation, on affiche "Consultation n°" suivi de l'identifiant du séjour
                // Sinon, on affiche "Séjour n°" suivi de l'identifiant du séjour
                StringBuilder infoSejour = new StringBuilder(Objects.equals(resultat.getString("Consultation"), "Y") ? "Consultation n°" : "Séjour n°");
                infoSejour.append(resultat.getString("idSejour"));
                infoSejour.append(" en ").append(dialogueBD.getNomService(resultat.getString("idService")));
                System.out.println(dialogueBD.getNomService(resultat.getString("idService")));
                infoSejour.append(" du ").append(resultat.getString("dateDebut"), 0, 10);
                if (resultat.getString("dateFin") != null) {
                    infoSejour.append(" au ").append(resultat.getString("dateFin"), 0, 10);
                }


                // Si le séjour est ouvert, on le met en premier
                if (Objects.equals(resultat.getString("ouvert"), "Y")) {
                    MenuDeroulantSejours.insertItemAt(infoSejour, 0);
                } else { // Sinon, on l'ajoute à la fin
                    MenuDeroulantSejours.addItem(infoSejour);
                }
                // On sélectionne le premier séjour par défaut
                MenuDeroulantSejours.setSelectedIndex(0);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Remplit la liste des actes du séjour sélectionné
     */
    public void remplirActes() {
        // On récupère les actes du séjour sélectionné
        // On effectue une recherche dans la table Acte avec l'identifiant du séjour sélectionné
        String sejourSelectionne = MenuDeroulantSejours.getSelectedItem().toString();
        // On extrait l'identifiant du séjour
        assert sejourSelectionne != null;
        if (sejourSelectionne.contains("Consultation")) {
            // On récupère l'identifiant de la consultation
            sejourSelectionne = sejourSelectionne.substring(15);
        } else {
            // On récupère l'identifiant du séjour
            sejourSelectionne = sejourSelectionne.substring(9);
        }
        // On enlève les caractères après l'identifiant
        String idSejour = sejourSelectionne.substring(0, sejourSelectionne.indexOf(" "));
        System.out.println("id serjour : " +idSejour);
        ArrayList<String> actes = new ArrayList<>();
        try (ResultSet resultat = dialogueBD.rechercheTable(
                "Acte",
                new HashMap<String, String>() {{
                    put("idSejour", idSejour);
                }},
                false)) {
            // On ajoute chaque acte du séjour dans la liste
            while (resultat.next()) {
                // On construit le texte à afficher dans la liste
                // On affiche le nom de l'acte suivi de la date de réalisation
                StringBuilder infoActe = new StringBuilder(resultat.getString("nom"));
                if(resultat.getString("dateRealisationActe") != null) {
                    infoActe.append(" le ").append(resultat.getString("dateRealisationActe"), 0, 10);
                }
                actes.add(infoActe.toString());
            }
            jList1.setListData(actes.toArray(new String[0]));
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adresse;
    private javax.swing.JLabel AdressePatient;
    private javax.swing.JLabel Ajout;
    private javax.swing.JLabel Alcool;
    private javax.swing.JLabel AlcoolPatient;
    private javax.swing.JButton BoutonAnesthesie;
    private javax.swing.JButton BoutonConsultation;
    private javax.swing.JButton BoutonExamenBiologique;
    private javax.swing.JButton BoutonPrescription;
    private javax.swing.JButton BoutonRadiologie;
    private javax.swing.JLabel DateNaissancePatient;
    private javax.swing.JLabel Fumeur;
    private javax.swing.JLabel FumeurPatient;
    private javax.swing.JLabel IPPPatient;
    private javax.swing.JComboBox MenuDeroulantSejours;
    private javax.swing.JLabel NeeLe;
    private javax.swing.JLabel NomPrenomPatient;
    private javax.swing.JPanel PanelBoutons;
    private javax.swing.JPanel PanneauCentral;
    private javax.swing.JPanel PanneauNord;
    private javax.swing.JPanel PanneauSud;
    private javax.swing.JLabel Sexe;
    private javax.swing.JLabel SexePatient;
    private javax.swing.JLabel Telephone;
    private javax.swing.JLabel TelephonePatient;
    private javax.swing.JButton boutonCloture;
    private javax.swing.JList jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomUtilisateur;
    private javax.swing.JPanel panelCloture;
    private javax.swing.JPanel panelSejourEtBoutons;
    // End of variables declaration//GEN-END:variables
}
