/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fc.DialogueBD;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Date;
import javax.swing.JTextField;

/**
 * @author emmaa
 */
public class AjoutPatient extends javax.swing.JFrame {

    /**
     * Creates new form AjoutPatient
     */

    private final DialogueBD dialogueBD;

    public AjoutPatient(DialogueBD dialogueBD, String langue) {
        initComponents();
        this.dialogueBD = dialogueBD;
        // Pour empêcher le redimensionnement de la fenêtre
        setResizable(false);
        // On change la langue de l'interface
        changerLangue(langue);
        //
        MenuDeroulantService.setModel(new javax.swing.DefaultComboBoxModel<>(dialogueBD.getNomServices().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexe = new javax.swing.ButtonGroup();
        buttonGroupChambreBox = new javax.swing.ButtonGroup();
        buttonGroupFumeur = new javax.swing.ButtonGroup();
        buttonGroupAlcool = new javax.swing.ButtonGroup();
        buttonGroupConsultation = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TexteAjouterUnPatient = new javax.swing.JLabel();
        OngletIdentite = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Nom = new javax.swing.JLabel();
        TexteNom = new javax.swing.JTextField();
        Prenom = new javax.swing.JLabel();
        TextePrenom = new javax.swing.JTextField();
        DateNaissance = new javax.swing.JLabel();
        sexe = new javax.swing.JLabel();
        Femme = new javax.swing.JRadioButton();
        Homme = new javax.swing.JRadioButton();
        Adresse = new javax.swing.JLabel();
        Voie = new javax.swing.JLabel();
        TexteAdresse = new javax.swing.JTextField();
        CodePostal = new javax.swing.JLabel();
        TexteCodePostal = new javax.swing.JTextField();
        Ville = new javax.swing.JLabel();
        TexteVille = new javax.swing.JTextField();
        Pays = new javax.swing.JLabel();
        TextePays = new javax.swing.JTextField();
        telephone = new javax.swing.JLabel();
        TexteTelephone = new javax.swing.JTextField();
        dateNaissanceChooser = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        fumeur = new javax.swing.JLabel();
        FumeurOui = new javax.swing.JRadioButton();
        FumeurNon = new javax.swing.JRadioButton();
        alcool = new javax.swing.JLabel();
        AlcoolOui = new javax.swing.JRadioButton();
        AlcoolNon = new javax.swing.JRadioButton();
        donneesSociales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TexteDonneesSociales = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        Service = new javax.swing.JLabel();
        MenuDeroulantService = new javax.swing.JComboBox();
        DateDebut = new javax.swing.JLabel();
        DateFin = new javax.swing.JLabel();
        Consultation = new javax.swing.JLabel();
        ConsultationOui = new javax.swing.JRadioButton();
        ConsultationNon = new javax.swing.JRadioButton();
        LocGeo = new javax.swing.JLabel();
        ServiceGeo = new javax.swing.JLabel();
        MeneDeroulantServiceGeo = new javax.swing.JComboBox();
        Chambre = new javax.swing.JLabel();
        ChambrePorte = new javax.swing.JRadioButton();
        ChambreFenetre = new javax.swing.JRadioButton();
        Box = new javax.swing.JLabel();
        Box1 = new javax.swing.JRadioButton();
        Box2 = new javax.swing.JRadioButton();
        Box3 = new javax.swing.JRadioButton();
        NumeroChambre = new javax.swing.JLabel();
        TexteNumeroChambre = new javax.swing.JTextField();
        dateDebutChooser = new com.toedter.calendar.JDateChooser();
        dateFinChooser = new com.toedter.calendar.JDateChooser();
        boutonAjouter = new javax.swing.JButton();
        labelIncomplet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TexteAjouterUnPatient.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        TexteAjouterUnPatient.setText("Ajouter un patient ");

        OngletIdentite.setBackground(new java.awt.Color(255, 255, 255));
        OngletIdentite.setForeground(new java.awt.Color(4, 66, 114));
        OngletIdentite.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nom.setText("Nom *");

        TexteNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexteNomActionPerformed(evt);
            }
        });

        Prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Prenom.setText("Prénom *");

        DateNaissance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DateNaissance.setText("Date de Naissance *");

        sexe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sexe.setText("Sexe");

        buttonGroupSexe.add(Femme);
        Femme.setText("Femme");

        buttonGroupSexe.add(Homme);
        Homme.setText("Homme");

        Adresse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Adresse.setText("Adresse");

        Voie.setText("N° et nom de voie");

        CodePostal.setText("Code Postal");

        Ville.setText("Ville");

        Pays.setText("Pays");

        telephone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        telephone.setText("Téléphone");

        dateNaissanceChooser.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TexteTelephone)
                    .addComponent(TexteNom)
                    .addComponent(TextePrenom)
                    .addComponent(TexteAdresse)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodePostal)
                            .addComponent(TexteCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ville)
                            .addComponent(TexteVille, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Pays)
                                .addGap(36, 36, 36))
                            .addComponent(TextePays, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sexe)
                            .addComponent(Nom)
                            .addComponent(Prenom)
                            .addComponent(DateNaissance)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Femme, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(Homme))
                            .addComponent(Adresse)
                            .addComponent(Voie)
                            .addComponent(telephone)
                            .addComponent(dateNaissanceChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TexteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Prenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DateNaissance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateNaissanceChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(sexe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Femme)
                    .addComponent(Homme))
                .addGap(18, 18, 18)
                .addComponent(Adresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Voie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TexteAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodePostal)
                    .addComponent(Ville)
                    .addComponent(Pays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TexteCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TexteVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextePays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telephone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TexteTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        OngletIdentite.addTab("Identité", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        fumeur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fumeur.setText("Fumeur");

        buttonGroupFumeur.add(FumeurOui);
        FumeurOui.setText("OUI");

        buttonGroupFumeur.add(FumeurNon);
        FumeurNon.setText("NON");

        alcool.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        alcool.setText("Alcool");

        buttonGroupAlcool.add(AlcoolOui);
        AlcoolOui.setText("OUI");

        buttonGroupAlcool.add(AlcoolNon);
        AlcoolNon.setText("NON");

        donneesSociales.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        donneesSociales.setText("Données sociales");

        jScrollPane1.setViewportView(TexteDonneesSociales);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fumeur)
                            .addComponent(alcool)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FumeurOui)
                                    .addComponent(AlcoolOui))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AlcoolNon)
                                    .addComponent(FumeurNon)))
                            .addComponent(donneesSociales))
                        .addGap(0, 380, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fumeur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FumeurOui)
                    .addComponent(FumeurNon))
                .addGap(18, 18, 18)
                .addComponent(alcool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlcoolOui)
                    .addComponent(AlcoolNon))
                .addGap(18, 18, 18)
                .addComponent(donneesSociales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        OngletIdentite.addTab("Données Médicales", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Service.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Service.setText("Service");

        MenuDeroulantService.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MenuDeroulantService.setForeground(new java.awt.Color(4, 66, 114));
        MenuDeroulantService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anapathologie", "Cardiologie", "Chirurgie", "Dermatologie", "Gynécologie", "Hématologie", "Immunologie", "Médecine Générale", "Neurologie", "Obstétrie", "Oncologie", "Pneumologie", "Psychiatrie", "Radiologie", "Réanimation", "Urologie", "Urgence" }));
        MenuDeroulantService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeroulantServiceActionPerformed(evt);
            }
        });

        DateDebut.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DateDebut.setText("Date de début *");

        DateFin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DateFin.setText("Date de fin");

        Consultation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Consultation.setText("Consultation *");

        buttonGroupConsultation.add(ConsultationOui);
        ConsultationOui.setText("Oui");

        buttonGroupConsultation.add(ConsultationNon);
        ConsultationNon.setText("Non");
        ConsultationNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultationNonActionPerformed(evt);
            }
        });

        LocGeo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LocGeo.setText("Localisation géographique");

        ServiceGeo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ServiceGeo.setText("Service");

        MeneDeroulantServiceGeo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anapathologie", "Cardiologie", "Chirurgie", "Dermatologie", "Gynécologie", "Hématologie", "Immunologie", "Médecine Générale", "Neurologie", "Obstétrie", "Oncologie", "Pneumologie", "Psychiatrie", "Radiologie", "Réanimation", "Urologie", "Urgence" }));

        Chambre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Chambre.setText("Chambre");

        buttonGroupChambreBox.add(ChambrePorte);
        ChambrePorte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ChambrePorte.setText("Porte");
        ChambrePorte.setActionCommand("P");

        buttonGroupChambreBox.add(ChambreFenetre);
        ChambreFenetre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ChambreFenetre.setText("Fenêtre");
        ChambreFenetre.setActionCommand("F");

        Box.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Box.setText("Box");

        buttonGroupChambreBox.add(Box1);
        Box1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Box1.setText("1");

        buttonGroupChambreBox.add(Box2);
        Box2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Box2.setText("2");

        buttonGroupChambreBox.add(Box3);
        Box3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Box3.setText("3");

        NumeroChambre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NumeroChambre.setText("Numéro de chambre");

        dateDebutChooser.setBackground(new java.awt.Color(255, 255, 255));
        dateDebutChooser.setDate(new Date());

        dateFinChooser.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuDeroulantService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MeneDeroulantServiceGeo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TexteNumeroChambre)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Consultation)
                            .addComponent(Service)
                            .addComponent(LocGeo)
                            .addComponent(ServiceGeo)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Chambre)
                                .addGap(138, 138, 138)
                                .addComponent(Box))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ChambrePorte)
                                .addGap(18, 18, 18)
                                .addComponent(ChambreFenetre)
                                .addGap(55, 55, 55)
                                .addComponent(Box1)
                                .addGap(18, 18, 18)
                                .addComponent(Box2)
                                .addGap(18, 18, 18)
                                .addComponent(Box3))
                            .addComponent(NumeroChambre)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DateDebut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ConsultationOui)
                                .addGap(27, 27, 27)
                                .addComponent(ConsultationNon))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateFinChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(dateDebutChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DateDebut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDebutChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(DateFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFinChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Consultation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultationOui)
                    .addComponent(ConsultationNon))
                .addGap(18, 18, 18)
                .addComponent(Service)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDeroulantService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LocGeo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceGeo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MeneDeroulantServiceGeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chambre)
                    .addComponent(Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChambrePorte)
                    .addComponent(ChambreFenetre)
                    .addComponent(Box1)
                    .addComponent(Box2)
                    .addComponent(Box3))
                .addGap(18, 18, 18)
                .addComponent(NumeroChambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TexteNumeroChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        OngletIdentite.addTab("Séjour", jPanel4);

        boutonAjouter.setBackground(new java.awt.Color(255, 255, 255));
        boutonAjouter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boutonAjouter.setForeground(new java.awt.Color(4, 66, 114));
        boutonAjouter.setText("Ajouter");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });

        labelIncomplet.setForeground(new java.awt.Color(255, 51, 51));
        labelIncomplet.setText("Veuillez remplir tous les champs marqués d'une *");
        labelIncomplet.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OngletIdentite)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TexteAjouterUnPatient)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(boutonAjouter)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelIncomplet)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TexteAjouterUnPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OngletIdentite, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIncomplet)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TexteNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexteNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexteNomActionPerformed

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed
        // On s'assure que le patient n'existe pas déjà (en se basant sur le nom, le prénom et la date de naissance)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format de la date

        if (!champsRemplis()) {
            labelIncomplet.setVisible(true);
        } else {
            if (dialogueBD.patientExiste(TexteNom.getText(), TextePrenom.getText(), sdf.format(dateNaissanceChooser.getDate()))) {
                // Si le patient existe déjà, on affiche un message d'erreur
                javax.swing.JOptionPane.showMessageDialog(null, "Le patient existe déjà");
                System.out.println("Le patient existe déjà");
            } else {
                // ------------------------ Récupération des données saisies par l'utilisateur ------------------------
                // On récupère les données saisies par l'utilisateur relatives au PATIENT
                String nom = TexteNom.getText();
                String prenom = TextePrenom.getText();
                String telephone = TexteTelephone.getText();
                String adresse = TexteAdresse.getText() + "-" + TexteCodePostal.getText() + " " + TexteVille.getText() + "-" + TextePays.getText();
                String donneesSociales = TexteDonneesSociales.getText();
                String dateNaissance = sdf.format(dateNaissanceChooser.getDate());
                // On récupère le sexe du patient (Femme, Homme ou null si rien n'est sélectionné)
                String sexe = Femme.isSelected() ? "F" : (Homme.isSelected() ? "M" : null);
                // On récupère si le patient est fumeur ou non (Oui, Non ou null si rien n'est sélectionné)
                String fumeur = FumeurOui.isSelected() ? "Y" : (FumeurNon.isSelected() ? "N" : null);
                // On récupère si le patient consomme de l'alcool ou non (Oui, Non ou null si rien n'est sélectionné)
                String alcool = AlcoolOui.isSelected() ? "Y" : (AlcoolNon.isSelected() ? "N" : null);
                // On crée un dictionnaire contenant les données du patient
                HashMap<String, String> dataPatient = new HashMap<>();
                dataPatient.put("nom", nom);
                dataPatient.put("prenom", prenom);
                dataPatient.put("dateNaissance", dateNaissance);
                dataPatient.put("sexe", sexe);
                dataPatient.put("adresse", adresse);
                dataPatient.put("dossierVisible", "Y");
                dataPatient.put("vivant", "Y");
                dataPatient.put("telephone", telephone);
                dataPatient.put("fumeur", fumeur);
                dataPatient.put("alcool", alcool);
                dataPatient.put("donneesSociales", donneesSociales);

                // On récupère les données relatives à la LOCALISATION GEOGRAPHIQUE
                // On récupère le service géographique sélectionné par l'utilisateur
                String serviceGeo = (String) MeneDeroulantServiceGeo.getSelectedItem();
                String idServiceGeo = dialogueBD.getIdService(serviceGeo); // On récupère l'id du service géographique
                String Lit = null;
                if (buttonGroupChambreBox.getSelection() != null) {
                    Lit = buttonGroupChambreBox.getSelection().getActionCommand();
                }
                System.out.println("LIIIIIIIT" + Lit);
                String idPiece = "-1";
                if (!TexteNumeroChambre.getText().isEmpty()) {
                    idPiece = TexteNumeroChambre.getText();
                }
                // On crée un dictionnaire contenant les données de la localisation géographique
                HashMap<String, String> dataLocG = new HashMap<>();
                dataLocG.put("idService", idServiceGeo);
                dataLocG.put("Lit", Lit);
                dataLocG.put("idPiece", idPiece);

                // On récupère les données relatives au SÉJOUR
                // On récupère les dates de début et de fin du séjour au format AAAA-MM-JJ
                String dateDebut = sdf.format(dateDebutChooser.getDate());
                String dateFin = null;
                if (dateFinChooser.getDate() != null) {
                    dateFin = sdf.format(dateFinChooser.getDate());
                }
                String consultation = ConsultationOui.isSelected() ? "Y" : (ConsultationNon.isSelected() ? "N" : null);
                String service = (String) MenuDeroulantService.getSelectedItem();
                // On crée un dictionnaire contenant les données du séjour
                HashMap<String, String> dataSejour = new HashMap<>();
                dataSejour.put("dateDebut", dateDebut);
                dataSejour.put("dateFin", dateFin);
                dataSejour.put("consultation", consultation);
                dataSejour.put("ouvert", "Y");
                dataSejour.put("idService", dialogueBD.getIdService(service));

                // TODO : Ajouter le médecin référent

                // ------------------------ Insertion dans la base de données ------------------------
                // 1 - On insère le patient dans la base de données et on récupère son id
                String idPatient;
                try {
                    idPatient = dialogueBD.insertPatient(dataPatient);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
                dataSejour.put("idPatient", idPatient);
                dataLocG.put("idPatient", idPatient);

                // 2 - On insère la localisation géographique dans la base de données et on récupère son id
                String idLocG;
                try {
                    idLocG = dialogueBD.insertLocG(dataLocG);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
                dataSejour.put("idLocG", idLocG); // On ajoute l'id de la localisation géographique au dictionnaire des données du séjour

                // 3 - On insère le séjour dans la base de données
                try {
                    dialogueBD.insertSejour(dataSejour);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }

                // On affiche un message de confirmation
                javax.swing.JOptionPane.showMessageDialog(null, "Le patient a été ajouté avec succès");
                System.out.println("Le patient a été ajouté avec succès");
            }
        }
        // Si le patient n'existe pas, on l'ajoute à la base de données
    }//GEN-LAST:event_boutonAjouterActionPerformed

    /**
     * Permet de vérifier si tous les champs obligatoires sont remplis
     *
     * @return true si tous les champs obligatoires sont remplis, false sinon
     */
    public boolean champsRemplis() {
        // On vérifie si le nom, le prénom et la date de naissance sont remplis
        if (TexteNom.getText().equals("") || TextePrenom.getText().equals("") || dateNaissanceChooser.getDate() == null) {
            return false;
        }
        // On vérifie si le service, la date de début et la consultation sont remplis
        if (dateDebutChooser.getDate() == null || buttonGroupConsultation.getSelection() == null) {
            return false;
        }
        labelIncomplet.setVisible(false);
        return true;
    }

    /**
     * Permet de changer la langue de l'interface
     *
     * @param langue : la langue choisie
     */
    public void changerLangue(String langue) {
        if (langue.equals("English")) {
            TexteAjouterUnPatient.setText("Add a patient");
            Nom.setText("Name");
            Prenom.setText("First name");
            DateNaissance.setText("Date of birth");
            sexe.setText("Sex");
            Femme.setText("Female");
            Homme.setText("Male");
            Adresse.setText("Address");
            Voie.setText("Street number and name");
            CodePostal.setText("Postal code");
            Ville.setText("City");
            Pays.setText("Country");
            telephone.setText("Phone number");
            fumeur.setText("Smoker");
            alcool.setText("Alcohol");
            donneesSociales.setText("Social data");
            Service.setText("Unit");
            boutonAjouter.setText("Add");
            // On change le titre des onglets
            OngletIdentite.setTitleAt(0, "Identity");
            OngletIdentite.setTitleAt(1, "Medical data");
            OngletIdentite.setTitleAt(2, "Unit");
        }
    }


    private void MenuDeroulantServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeroulantServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDeroulantServiceActionPerformed

    private void ConsultationNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultationNonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultationNonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // On instancie un objet DialogueBD pour communiquer avec la base de données
                DialogueBD dialogueBD = new DialogueBD();
                // On se connecte à la base de données
                dialogueBD.connect();
                // On instancie l'interface d'ajout de patient
                new AjoutPatient(dialogueBD, "Français").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adresse;
    private javax.swing.JRadioButton AlcoolNon;
    private javax.swing.JRadioButton AlcoolOui;
    private javax.swing.JLabel Box;
    private javax.swing.JRadioButton Box1;
    private javax.swing.JRadioButton Box2;
    private javax.swing.JRadioButton Box3;
    private javax.swing.JLabel Chambre;
    private javax.swing.JRadioButton ChambreFenetre;
    private javax.swing.JRadioButton ChambrePorte;
    private javax.swing.JLabel CodePostal;
    private javax.swing.JLabel Consultation;
    private javax.swing.JRadioButton ConsultationNon;
    private javax.swing.JRadioButton ConsultationOui;
    private javax.swing.JLabel DateDebut;
    private javax.swing.JLabel DateFin;
    private javax.swing.JLabel DateNaissance;
    private javax.swing.JRadioButton Femme;
    private javax.swing.JRadioButton FumeurNon;
    private javax.swing.JRadioButton FumeurOui;
    private javax.swing.JRadioButton Homme;
    private javax.swing.JLabel LocGeo;
    private javax.swing.JComboBox MeneDeroulantServiceGeo;
    private javax.swing.JComboBox MenuDeroulantService;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel NumeroChambre;
    private javax.swing.JTabbedPane OngletIdentite;
    private javax.swing.JLabel Pays;
    private javax.swing.JLabel Prenom;
    private javax.swing.JLabel Service;
    private javax.swing.JLabel ServiceGeo;
    private javax.swing.JTextField TexteAdresse;
    private javax.swing.JLabel TexteAjouterUnPatient;
    private javax.swing.JTextField TexteCodePostal;
    private javax.swing.JTextPane TexteDonneesSociales;
    private javax.swing.JTextField TexteNom;
    private javax.swing.JTextField TexteNumeroChambre;
    private javax.swing.JTextField TextePays;
    private javax.swing.JTextField TextePrenom;
    private javax.swing.JTextField TexteTelephone;
    private javax.swing.JTextField TexteVille;
    private javax.swing.JLabel Ville;
    private javax.swing.JLabel Voie;
    private javax.swing.JLabel alcool;
    private javax.swing.JButton boutonAjouter;
    private javax.swing.ButtonGroup buttonGroupAlcool;
    private javax.swing.ButtonGroup buttonGroupChambreBox;
    private javax.swing.ButtonGroup buttonGroupConsultation;
    private javax.swing.ButtonGroup buttonGroupFumeur;
    private javax.swing.ButtonGroup buttonGroupSexe;
    private com.toedter.calendar.JDateChooser dateDebutChooser;
    private com.toedter.calendar.JDateChooser dateFinChooser;
    private com.toedter.calendar.JDateChooser dateNaissanceChooser;
    private javax.swing.JLabel donneesSociales;
    private javax.swing.JLabel fumeur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIncomplet;
    private javax.swing.JLabel sexe;
    private javax.swing.JLabel telephone;
    // End of variables declaration//GEN-END:variables
}
