/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fc.DialogueBD;
import fc.Utilisateur;

/**
 *
 * @author Clémence
 */
public class AjoutPersonnelMedical extends javax.swing.JFrame {

    /**
     * Creates new form AjoutMedecin
     */
    private DialogueBD dialogueBD;
    private Utilisateur utilisateur;
    private String idSejour;
    
    public AjoutPersonnelMedical() {
        initComponents();
        setResizable(false); 
        //Pour basculer l'interface en anglais lorsqu'elle la langue "English" est sélectionnée
        changerLangue(this.utilisateur.getLangue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TexteAjouterUnMédecin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EtiquetteNom = new javax.swing.JLabel();
        ChampNumTel = new javax.swing.JTextField();
        EtiquettePoste = new javax.swing.JLabel();
        ChampNom = new javax.swing.JTextField();
        EtiquetteService = new javax.swing.JLabel();
        MenuDeroulantService = new javax.swing.JComboBox();
        EtiquetteDate = new javax.swing.JLabel();
        ChampPoste = new javax.swing.JTextField();
        EtiquetteRC = new javax.swing.JLabel();
        CheckAttachéRC = new javax.swing.JCheckBox();
        BoutonAjouterSpé = new javax.swing.JButton();
        EtiquetteRPPS = new javax.swing.JLabel();
        ChampPrenom = new javax.swing.JTextField();
        EtiquetteID = new javax.swing.JLabel();
        ChampMDP = new javax.swing.JTextField();
        EtiquettePrenom = new javax.swing.JLabel();
        ChampRPPS = new javax.swing.JTextField();
        BoutonAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 242, 254));

        TexteAjouterUnMédecin.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        TexteAjouterUnMédecin.setText("Ajouter un personnel médical");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        EtiquetteNom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquetteNom.setText("Nom");

        EtiquettePoste.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquettePoste.setText("Poste");

        ChampNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChampNomActionPerformed(evt);
            }
        });

        EtiquetteService.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquetteService.setText("Service");

        MenuDeroulantService.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MenuDeroulantService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anapathologie", "Cardiologie", "Chirurgie", "Dermatologie", "Gynécologie", "Hématologie", "Immunologie", "Médecine Générale", "Neurologie", "Obstétrie", "Oncologie", "Pneumologie", "Psychiatrie", "Radiologie", "Réanimation", "Urologie", "Urgence" }));

        EtiquetteDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquetteDate.setText("Date de fin de contrat");

        EtiquetteRC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquetteRC.setText("Recherche Clinique");

        CheckAttachéRC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CheckAttachéRC.setText("Attaché de recherche clinique");

        BoutonAjouterSpé.setBackground(new java.awt.Color(4, 66, 114));
        BoutonAjouterSpé.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BoutonAjouterSpé.setForeground(new java.awt.Color(255, 255, 255));
        BoutonAjouterSpé.setText("Ajouter une spécialité");

        EtiquetteRPPS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquetteRPPS.setText("Numéro RPPS");

        ChampPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChampPrenomActionPerformed(evt);
            }
        });

        EtiquetteID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquetteID.setText("Mot de passe");

        EtiquettePrenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EtiquettePrenom.setText("Prénom");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MenuDeroulantService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetteNom)
                            .addComponent(ChampNom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChampPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiquettePrenom))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ChampPoste)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BoutonAjouterSpé)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EtiquetteID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckAttachéRC)
                            .addComponent(EtiquetteRC)
                            .addComponent(EtiquetteRPPS)
                            .addComponent(EtiquettePoste)
                            .addComponent(EtiquetteService)
                            .addComponent(EtiquetteDate))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ChampNumTel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChampMDP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChampRPPS))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ChampPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChampNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EtiquetteNom)
                            .addComponent(EtiquettePrenom))
                        .addGap(35, 35, 35)))
                .addGap(26, 26, 26)
                .addComponent(EtiquetteRPPS)
                .addGap(1, 1, 1)
                .addComponent(ChampRPPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(EtiquetteID)
                .addGap(2, 2, 2)
                .addComponent(ChampMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(EtiquetteDate)
                .addGap(4, 4, 4)
                .addComponent(ChampNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(EtiquetteService)
                .addGap(4, 4, 4)
                .addComponent(MenuDeroulantService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoutonAjouterSpé)
                .addGap(7, 7, 7)
                .addComponent(EtiquettePoste)
                .addGap(4, 4, 4)
                .addComponent(ChampPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(EtiquetteRC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckAttachéRC)
                .addContainerGap())
        );

        BoutonAjouter.setBackground(new java.awt.Color(4, 66, 114));
        BoutonAjouter.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        BoutonAjouter.setForeground(new java.awt.Color(255, 255, 255));
        BoutonAjouter.setText("Ajouter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TexteAjouterUnMédecin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(BoutonAjouter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TexteAjouterUnMédecin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BoutonAjouter)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChampPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChampPrenomActionPerformed
        
    }//GEN-LAST:event_ChampPrenomActionPerformed

    private void ChampNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChampNomActionPerformed
        
    }//GEN-LAST:event_ChampNomActionPerformed
    public void changerLangue(String langue) {
        //Si la langue selectionnée lors la connexion est l'anglais, alors l'interface s'affiche en anglais
        //On remplace chaque composant par son équivalent anglais
        if (langue.equals("English")) {
            TexteAjouterUnMédecin.setText("Add medical staff");
            EtiquetteNom.setText("Last name");
            EtiquettePrenom.setText("First name");
            EtiquetteRPPS.setText("RPPS number");
            EtiquetteID.setText("Password");
            EtiquetteDate.setText("End date of contract");
            EtiquetteService.setText("Medical service");
            EtiquettePoste.setText("Profession");
            EtiquetteRC.setText("Clinical research");
            CheckAttachéRC.setText("Clinical research associate");
            BoutonAjouterSpé.setText("Add a department");
            BoutonAjouter.setText("Add");
      }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAjouter;
    private javax.swing.JButton BoutonAjouterSpé;
    private javax.swing.JTextField ChampMDP;
    private javax.swing.JTextField ChampNom;
    private javax.swing.JTextField ChampNumTel;
    private javax.swing.JTextField ChampPoste;
    private javax.swing.JTextField ChampPrenom;
    private javax.swing.JTextField ChampRPPS;
    private javax.swing.JCheckBox CheckAttachéRC;
    private javax.swing.JLabel EtiquetteDate;
    private javax.swing.JLabel EtiquetteID;
    private javax.swing.JLabel EtiquetteNom;
    private javax.swing.JLabel EtiquettePoste;
    private javax.swing.JLabel EtiquettePrenom;
    private javax.swing.JLabel EtiquetteRC;
    private javax.swing.JLabel EtiquetteRPPS;
    private javax.swing.JLabel EtiquetteService;
    private javax.swing.JComboBox MenuDeroulantService;
    private javax.swing.JLabel TexteAjouterUnMédecin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
