/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.JTextField;

import fc.Utilisateur;
import fc.AfficherListePatientsListener;
import fc.DialogueBD;

/**
 *
 * @author Camil
 */
public class AjoutPatientEtude extends javax.swing.JFrame implements AfficherListePatientsListener {

    private DialogueBD dialogueBD;
    private Utilisateur utilisateur;
    private ArrayList<AfficherListePatientsListener> patientSelectioneListenerList = new ArrayList<>();
    private String idEtude;

    /**
     * Creates new form AjoutPatientEtude
     */
    public AjoutPatientEtude(DialogueBD dialogueBD, Utilisateur utilisateur, String idEtude) {
        this.dialogueBD = dialogueBD;
        this.utilisateur = utilisateur;
        this.idEtude = idEtude;
        initComponents();
        changerLangue(this.utilisateur.getLangue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        PanneauNord = new javax.swing.JPanel();
        RechercherUnPatient = new javax.swing.JLabel();
        BoutonRechercher = new javax.swing.JButton();
        IPP = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        texteIPP = new javax.swing.JTextField();
        Prenom = new javax.swing.JLabel();
        texteNom = new javax.swing.JTextField();
        textePrenom = new javax.swing.JTextField();
        PanneauSud = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(745, 439));
        setBackground(new java.awt.Color(255, 255, 255));

        Panel.setPreferredSize(new java.awt.Dimension(745, 439));
        Panel.setLayout(new java.awt.BorderLayout());

        PanneauNord.setPreferredSize(new java.awt.Dimension(745, 200));

        RechercherUnPatient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RechercherUnPatient.setText(" Rechercher un patient :");
        RechercherUnPatient.setPreferredSize(new Dimension(400,75));

        BoutonRechercher.setBackground(new java.awt.Color(4, 66, 114));
        BoutonRechercher.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonRechercher.setForeground(new java.awt.Color(255, 255, 255));
        BoutonRechercher.setText("Rechercher");
        BoutonRechercher.setPreferredSize(new java.awt.Dimension(97, 40));
        BoutonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRechercherActionPerformed(evt);
            }
        });

        IPP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        IPP.setText("IPP");

        Nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nom.setText("Nom ");

        texteIPP.setName("idPatient"); // NOI18N
        texteIPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteIPPActionPerformed(evt);
            }
        });
        texteIPP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                texteIPPPropertyChange(evt);
            }
        });

        Prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Prenom.setText("Prénom");

        texteNom.setName("nom"); // NOI18N
        texteNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteNomActionPerformed(evt);
            }
        });

        textePrenom.setName("prenom"); // NOI18N

        javax.swing.GroupLayout PanneauNordLayout = new javax.swing.GroupLayout(PanneauNord);
        PanneauNord.setLayout(PanneauNordLayout);
        PanneauNordLayout.setHorizontalGroup(
            PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauNordLayout.createSequentialGroup()
                .addComponent(RechercherUnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauNordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauNordLayout.createSequentialGroup()
                        .addComponent(IPP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texteIPP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(Nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texteNom, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauNordLayout.createSequentialGroup()
                        .addComponent(BoutonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(49, 49, 49)
                .addComponent(Prenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        PanneauNordLayout.setVerticalGroup(
            PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauNordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RechercherUnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanneauNordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPP)
                    .addComponent(texteIPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nom)
                    .addComponent(texteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prenom)
                    .addComponent(textePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BoutonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Panel.add(PanneauNord, java.awt.BorderLayout.NORTH);

        PanneauSud.setPreferredSize(new java.awt.Dimension(745, 200));
        PanneauSud.setLayout(new java.awt.BorderLayout());
        Panel.add(PanneauSud, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texteIPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteIPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteIPPActionPerformed

    private void BoutonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRechercherActionPerformed
        // -------------------- On récupère la liste des patients qui correspondent à la recherche ---------------------
        // On récupère les champs de la recherche dans une HashMap
        HashMap<String, String> dataPatient = new HashMap<>();
        // Pour chaque component, on vérifie si c'est un JTextField, si c'est le cas, on ajoute le contenu du JTextField dans la HashMap
        for (Component component : PanneauNord.getComponents()) {
            if (component instanceof JTextField) {
                JTextField textField = (JTextField) component;
                if (!textField.getText().isEmpty()) { // On vérifie que le JTextField ne soit pas vide
                    dataPatient.put(textField.getName(), textField.getText());
                }
            }
        }

        //On récupère les patients qui correspondent à la recherche
        ResultSet resultSetPatients = dialogueBD.getPatients(dataPatient);

        AfficherListePatients afficherListePatients = new AfficherListePatients(resultSetPatients, utilisateur.getLangue());
        afficherListePatients.addPatientSelectedListener(this);

        // ---------------- On affiche la liste des patients qui correspondent à la recherche -----------------------
        //On supprime tous les composants du panneau sud
        for (Component component : PanneauSud.getComponents()) {
            PanneauSud.remove(component);
        }
        //On ajoute le JScrollPane au panneau principal
        PanneauSud.add(afficherListePatients, java.awt.BorderLayout.CENTER);
        //On actualise le panneau principal
        PanneauSud.repaint();
        this.pack();
        PanneauSud.revalidate();
    }//GEN-LAST:event_BoutonRechercherActionPerformed

    private void texteNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteNomActionPerformed

    private void texteIPPPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_texteIPPPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_texteIPPPropertyChange

    @Override
    public void patientSelected(String idPatient) {
        if(utilisateur.isArc()){
            System.out.println("Selected: " + idPatient);

            //Vérification que le patient n'est pas dans la table EtudePatient
            String verifPatient = "SELECT * from EtudePatient WHERE idPatient = " + idPatient + " AND idEtude = "+idEtude;
            ResultSet resultSet = dialogueBD.requete(verifPatient);

            try {
                if( resultSet.next() ){
                    // Si le test est réussi, alors le patient est déjà dans l'étude
                    javax.swing.JOptionPane.showMessageDialog(null, "Patient est déjà dans l'étude");
                    this.dispose();
                }
                else{
                    // On prévient tous les listeners que l'utilisateur a sélectionné un patient
                    for (AfficherListePatientsListener afficherListePatientsListener : patientSelectioneListenerList) {
                        afficherListePatientsListener.patientSelected((String) idPatient);
                    }
                    //Création de la requête SQL
                    String requete = "Insert into EtudePatient (idEtude,idPatient) values (" + idEtude + "," + idPatient + ")";
                    //Vérification de la requête demandée
                    String verif = requete.toString();
                    System.out.println(verif);
                    //Exécution de la requête
                    dialogueBD.requete(requete);
                    // On affiche un message de confirmation
                    javax.swing.JOptionPane.showMessageDialog(null, "Patient a été ajouté avec succès à l'étude");
                    this.dispose();
                    
                    //On actualise le panneau principal
                    PanneauSud.repaint();
                    this.pack();
                    PanneauSud.revalidate();
                }
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

    public void changerLangue(String langue){
        if(langue.equals("English")){
            BoutonRechercher.setText("Search");
            IPP.setText("PPI");
            Nom.setText("Last Name");
            Prenom.setText("First Name");
            RechercherUnPatient.setText("Search for a patient");
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            final Utilisateur utilisateur = new Utilisateur("Cot", "Harry", true, "Français", 1, 2222, "Y");
            final DialogueBD dialogueBD = new DialogueBD();
            final String idEtude = "1";
            {
                dialogueBD.connect();
            }
            public void run() {
                new AjoutPatientEtude(dialogueBD, utilisateur,idEtude).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonRechercher;
    private javax.swing.JLabel IPP;
    private javax.swing.JLabel Nom;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel PanneauNord;
    private javax.swing.JPanel PanneauSud;
    private javax.swing.JLabel Prenom;
    private javax.swing.JLabel RechercherUnPatient;
    private javax.swing.JTextField texteIPP;
    private javax.swing.JTextField texteNom;
    private javax.swing.JTextField textePrenom;
    // End of variables declaration//GEN-END:variables

}


