/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author emmaa
 */
public class AjouterEtude extends javax.swing.JFrame {

    /**
     * Creates new form AjouterEtude
     */
    public AjouterEtude() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CreerEtude = new javax.swing.JLabel();
        TypeRecherche = new javax.swing.JLabel();
        MenuDeroulantTypeRecherche = new javax.swing.JComboBox();
        IntituleEtude = new javax.swing.JLabel();
        TexteIntitule = new javax.swing.JTextField();
        NomPraticienHospitalier = new javax.swing.JLabel();
        TextNomPraticienHospitalier = new javax.swing.JTextField();
        DateDemarrage = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        BoutonCreer = new javax.swing.JButton();
        Duree = new javax.swing.JLabel();
        DureeValeur = new javax.swing.JTextField();
        RadioButtonJours = new javax.swing.JRadioButton();
        RadioButtonMois = new javax.swing.JRadioButton();
        RadioButtonAnnees = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CreerEtude.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CreerEtude.setText("Créer une étude ");

        TypeRecherche.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TypeRecherche.setText("Type de recherche ");

        MenuDeroulantTypeRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "étude de nouveaux traitements médicamenteux/nouvelles molécules thérapeutiques", "suivi de médicaments déjà utilisés en clinique", "validation et développement de nouveaux dispositifs médicaux " }));
        MenuDeroulantTypeRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeroulantTypeRechercheActionPerformed(evt);
            }
        });

        IntituleEtude.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IntituleEtude.setText("Intitulé de l'étude ");

        TexteIntitule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexteIntituleActionPerformed(evt);
            }
        });

        NomPraticienHospitalier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NomPraticienHospitalier.setText("Nom du praticien hospitalier");

        DateDemarrage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DateDemarrage.setText("Date de démarrage");

        BoutonCreer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonCreer.setText("Créer");

        Duree.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Duree.setText("Durée");

        buttonGroup1.add(RadioButtonJours);
        RadioButtonJours.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RadioButtonJours.setText("Jours");

        buttonGroup1.add(RadioButtonMois);
        RadioButtonMois.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RadioButtonMois.setText("Mois");

        buttonGroup1.add(RadioButtonAnnees);
        RadioButtonAnnees.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RadioButtonAnnees.setText("Années");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNomPraticienHospitalier)
                    .addComponent(TexteIntitule)
                    .addComponent(MenuDeroulantTypeRecherche, 0, 469, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreerEtude)
                            .addComponent(TypeRecherche)
                            .addComponent(IntituleEtude)
                            .addComponent(NomPraticienHospitalier)
                            .addComponent(DateDemarrage)
                            .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Duree)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BoutonCreer)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DureeValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioButtonJours)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioButtonMois)))
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonAnnees)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreerEtude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TypeRecherche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDeroulantTypeRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IntituleEtude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TexteIntitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(NomPraticienHospitalier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNomPraticienHospitalier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DateDemarrage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Duree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DureeValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonJours)
                    .addComponent(RadioButtonMois)
                    .addComponent(RadioButtonAnnees))
                .addGap(27, 27, 27)
                .addComponent(BoutonCreer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDeroulantTypeRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeroulantTypeRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDeroulantTypeRechercheActionPerformed

    private void TexteIntituleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexteIntituleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexteIntituleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterEtude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterEtude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterEtude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEtude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterEtude().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonCreer;
    private javax.swing.JLabel CreerEtude;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JLabel DateDemarrage;
    private javax.swing.JLabel Duree;
    private javax.swing.JTextField DureeValeur;
    private javax.swing.JLabel IntituleEtude;
    private javax.swing.JComboBox MenuDeroulantTypeRecherche;
    private javax.swing.JLabel NomPraticienHospitalier;
    private javax.swing.JRadioButton RadioButtonAnnees;
    private javax.swing.JRadioButton RadioButtonJours;
    private javax.swing.JRadioButton RadioButtonMois;
    private javax.swing.JTextField TextNomPraticienHospitalier;
    private javax.swing.JTextField TexteIntitule;
    private javax.swing.JLabel TypeRecherche;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
