/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fc.DialogueBD;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;

/**
 *
 * @author Antoine
 */
public class ClotureSejour extends javax.swing.JFrame {

    public final DialogueBD dialogueBD;
    public final String idSejour;
    public  String idPatient;

    /**
     * Creates new form ClotureSejour
     */
    public ClotureSejour(DialogueBD dialogueBD, String idSejour) {
        this.dialogueBD = dialogueBD;
        this.idSejour = idSejour;
        initComponents();
        String requeteSejour = "SELECT OUVERT,  LettreDeSortie, idPatient FROM Sejour WHERE idSejour = " + idSejour;
        ResultSet resultatSejour = dialogueBD.requete(requeteSejour);
        try {
            resultatSejour.next();
            idPatient = resultatSejour.getString("idPatient");
            // Si le séjour est déjà fermé, on cache le bouton de clôture (lecture seule)
            if (resultatSejour.getString("OUVERT").equals("N")) {
                boutonCloture.setVisible(false);
                // On affiche la lettre de sortie
                texteLettreDeSortie.setEditable(false);
                texteLettreDeSortie.setText(resultatSejour.getString("LettreDeSortie"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelLettre = new javax.swing.JPanel();
        labelLettreSortie = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texteLettreDeSortie = new javax.swing.JTextArea();
        panelBouton = new javax.swing.JPanel();
        boutonCloture = new javax.swing.JButton();
        labelErreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelLettre.setBackground(new java.awt.Color(255, 255, 255));

        labelLettreSortie.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        labelLettreSortie.setForeground(new java.awt.Color(4, 66, 114));
        labelLettreSortie.setText("Lettre de Sortie :");

        texteLettreDeSortie.setColumns(20);
        texteLettreDeSortie.setRows(5);
        jScrollPane1.setViewportView(texteLettreDeSortie);

        javax.swing.GroupLayout panelLettreLayout = new javax.swing.GroupLayout(panelLettre);
        panelLettre.setLayout(panelLettreLayout);
        panelLettreLayout.setHorizontalGroup(
            panelLettreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLettreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLettreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(panelLettreLayout.createSequentialGroup()
                        .addComponent(labelLettreSortie)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLettreLayout.setVerticalGroup(
            panelLettreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLettreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLettreSortie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPrincipal.add(panelLettre, java.awt.BorderLayout.NORTH);

        panelBouton.setBackground(new java.awt.Color(255, 255, 255));
        panelBouton.setLayout(new javax.swing.BoxLayout(panelBouton, javax.swing.BoxLayout.Y_AXIS));

        boutonCloture.setBackground(new java.awt.Color(255, 255, 255));
        boutonCloture.setForeground(new java.awt.Color(4, 66, 114));
        boutonCloture.setText("Cloturer");
        boutonCloture.setAlignmentX(Component.CENTER_ALIGNMENT);
        boutonCloture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonClotureActionPerformed(evt);
            }
        });
        panelBouton.add(Box.createVerticalGlue());
        panelBouton.add(boutonCloture);
        panelBouton.add(Box.createVerticalGlue());

        labelErreur.setForeground(new java.awt.Color(255, 51, 51));
        labelErreur.setText("Veuillez remplir la lettre de sortie");
        labelErreur.setAlignmentX(Component.CENTER_ALIGNMENT);
        panelBouton.add(Box.createVerticalGlue());
        panelBouton.add(labelErreur);
        panelBouton.add(Box.createVerticalGlue());
        labelErreur.setVisible(false);

        panelPrincipal.add(panelBouton, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonClotureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonClotureActionPerformed
        // On vérifie que le texte de la lettre de sortie n'est pas vide
        if (texteLettreDeSortie.getText().isEmpty()) {
            labelErreur.setVisible(true);
            this.pack();
        } else {
            // On clôture le séjour
            String requete = "UPDATE Sejour SET Ouvert = 'N', LettreDeSortie='" + texteLettreDeSortie.getText().replace("'","''") +"', DateFin = Current_Date "+" WHERE idSejour = " + idSejour;
            dialogueBD.requete(requete);
            // On met à jour le statut du patient
            String requetePatient = "UPDATE Patient SET DossierVisible = 'N' WHERE idPatient = " + idPatient;
            dialogueBD.requete(requetePatient);
            this.dispose();
        }
    }//GEN-LAST:event_boutonClotureActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonCloture;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelErreur;
    private javax.swing.JLabel labelLettreSortie;
    private javax.swing.JPanel panelBouton;
    private javax.swing.JPanel panelLettre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea texteLettreDeSortie;
    // End of variables declaration//GEN-END:variables
}
