/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AjoutActe;

import fc.DialogueBD;
import fc.Utilisateur;
import java.util.Date;
import java.util.HashMap;

/**
 *
 * @author emmaa
 */
public class AjoutExamenBiologique extends javax.swing.JFrame {

    /**
     * Creates new form AjoutExamenBiologique
     */
    private DialogueBD dialogueBD;
    private Utilisateur utilisateur;
    private String idSejour;

    public AjoutExamenBiologique(DialogueBD dialogueBD, Utilisateur utilisateur,String idSejour) {
        initComponents();
        //Pour empêcher le redimensionnement de la fenêtre, on utilise setResizable(false)
        setResizable(false);
        this.dialogueBD = dialogueBD;
        this.utilisateur = utilisateur;
        this.idSejour = idSejour;
        //On appelle la méthode changerLangue pour mettre l'interface en anglais ou en français 
        changerLangue(this.utilisateur.getLangue());
        //On définit la date maximale de demande d'examen biologique à la date du jour
        DateChooser.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AjouterUnExamenBiologique = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        Date = new javax.swing.JLabel();
        TypeDExamen = new javax.swing.JLabel();
        BoutonAjouter = new javax.swing.JButton();
        MenuDeroulantTypeExamen = new javax.swing.JComboBox();
        Commentaire = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ZoneCommentaire = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 242, 254));

        AjouterUnExamenBiologique.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AjouterUnExamenBiologique.setText("Ajouter un examen biologique ");

        Date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Date.setText("Date de demande");

        TypeDExamen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TypeDExamen.setText("Type d'examen");

        BoutonAjouter.setBackground(new java.awt.Color(4, 66, 114));
        BoutonAjouter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonAjouter.setForeground(new java.awt.Color(255, 255, 255));
        BoutonAjouter.setText("Ajouter");
        BoutonAjouter.setActionCommand("");
        BoutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAjouterActionPerformed(evt);
            }
        });

        MenuDeroulantTypeExamen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biochimie", "Génétique", "Hématologie", "Immunologie", "Microbiologie", "Sérologie" }));

        Commentaire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Commentaire.setText("Commentaire");

        ZoneCommentaire.setColumns(20);
        ZoneCommentaire.setRows(5);
        jScrollPane1.setViewportView(ZoneCommentaire);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AjouterUnExamenBiologique)
                    .addComponent(TypeDExamen)
                    .addComponent(MenuDeroulantTypeExamen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BoutonAjouter)
                        .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Commentaire)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AjouterUnExamenBiologique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TypeDExamen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDeroulantTypeExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Commentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(BoutonAjouter)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAjouterActionPerformed
        // Récupération des données
        Date date = DateChooser.getDate();
        String commentaire = MenuDeroulantTypeExamen.getSelectedItem()+ " "+ ZoneCommentaire.getText();
        String dateExamenBio = new java.sql.Date(date.getTime()).toString();
        
        //On entre les données dans la hashmap
        HashMap<String, String> examenBioData = new HashMap<String, String>();
        examenBioData.put("nom", "Examen Biologique");
        examenBioData.put("datePrescription",dateExamenBio);
        examenBioData.put("commentaire",commentaire);
        examenBioData.put("idSejour",idSejour);
        examenBioData.put("idPrescripteur", utilisateur.getIdUtilisateur());
        // On envoie les données à la base de données
        dialogueBD.insertActe(examenBioData);
        // On ferme la fenêtre
        this.dispose();
        
    }//GEN-LAST:event_BoutonAjouterActionPerformed


    public void changerLangue(String langue) {
        //Si la langue selectionnée lors la connexion est l'anglais, alors l'interface s'affiche en anglais
        //On remplace chaque composant par son équivalent anglais
        if (langue.equals("English")) {
            AjouterUnExamenBiologique.setText("Add a biological examination");
            TypeDExamen.setText("Type of examination");
            Commentaire.setText("Comment");
            BoutonAjouter.setText("Add");
            Date.setText("Date of request");
            MenuDeroulantTypeExamen.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Biochemistry","Genetic","Hematology","Immunology","Microbiology","Serology"}));           
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutExamenBiologique(new DialogueBD(),new Utilisateur("Cot","Harry",true,"Français", 1,1111,"Y"),"3").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AjouterUnExamenBiologique;
    private javax.swing.JButton BoutonAjouter;
    private javax.swing.JLabel Commentaire;
    private javax.swing.JLabel Date;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JComboBox MenuDeroulantTypeExamen;
    private javax.swing.JLabel TypeDExamen;
    private javax.swing.JTextArea ZoneCommentaire;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
