/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AjoutActe;

import fc.DialogueBD;
import fc.Utilisateur;

/**
 *
 * @author emmaa
 */
public class AjouterRadiologie extends javax.swing.JFrame {

    /**
     * Creates new form AjouterRadiologie
     */
    
        private DialogueBD dialogueBD;
        private Utilisateur utilisateur;
        private String idSejour;
        
    public AjouterRadiologie(DialogueBD dialogueBD, Utilisateur utilisateur,String idSejour) {
        initComponents();
        //Pour empêcher le redimensionnement de la fenêtre, on utilise setResizable(false)
        setResizable(false);
        this.dialogueBD = dialogueBD;
        this.utilisateur = utilisateur;
        this.idSejour = idSejour;
        changerLangue(this.utilisateur.getLangue());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DemandeExamenRadiologie = new javax.swing.JLabel();
        TypeExamen = new javax.swing.JLabel();
        BoutonRadiographie = new javax.swing.JRadioButton();
        BoutonEchographie = new javax.swing.JRadioButton();
        BoutonScanner = new javax.swing.JRadioButton();
        BoutonIRM = new javax.swing.JRadioButton();
        BoutonScintigraphie = new javax.swing.JRadioButton();
        BoutonTomographie = new javax.swing.JRadioButton();
        Date = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        Commentaire = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ZoneCommentaire = new javax.swing.JTextArea();
        BoutonAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DemandeExamenRadiologie.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DemandeExamenRadiologie.setText("Demande d'examen(s) radiologique(s)");

        TypeExamen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TypeExamen.setText("Type(s) d'examen(s)");

        BoutonRadiographie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonRadiographie.setText("Radiographie");

        BoutonEchographie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonEchographie.setText("Echographie");

        BoutonScanner.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonScanner.setText("Scanner");

        BoutonIRM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonIRM.setText("IRM");

        BoutonScintigraphie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonScintigraphie.setText("Scintigraphie");

        BoutonTomographie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonTomographie.setText("Tomographie");

        Date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Date.setText("Date");

        Commentaire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Commentaire.setText("Commentaire");

        ZoneCommentaire.setColumns(20);
        ZoneCommentaire.setRows(5);
        jScrollPane1.setViewportView(ZoneCommentaire);

        BoutonAjouter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BoutonAjouter.setText("Ajouter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DemandeExamenRadiologie)
                            .addComponent(TypeExamen)
                            .addComponent(Date)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(DateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BoutonRadiographie)
                                            .addComponent(BoutonScintigraphie))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BoutonEchographie)
                                            .addComponent(BoutonTomographie))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BoutonScanner)
                                    .addComponent(BoutonIRM)))
                            .addComponent(Commentaire))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(BoutonAjouter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DemandeExamenRadiologie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TypeExamen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonRadiographie)
                    .addComponent(BoutonEchographie)
                    .addComponent(BoutonScanner))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonScintigraphie)
                    .addComponent(BoutonTomographie)
                    .addComponent(BoutonIRM))
                .addGap(18, 18, 18)
                .addComponent(Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Commentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoutonAjouter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void changerLangue(String langue) {
         //Si la langue selectionnée lors la connexion est l'anglais, alors l'interface s'affiche en anglais
         //On remplace chaque composant par son équivalent anglais
        if(langue.equals("English")){
            DemandeExamenRadiologie.setText("Request for radiological examination");
            TypeExamen.setText("Type(s) of examination(s)");
            Commentaire.setText("Comment");
            BoutonEchographie.setText("Ultrasound");
            BoutonIRM.setText("MRI");
            BoutonRadiographie.setText("X-Ray");
            BoutonScanner.setText("");
            BoutonScintigraphie.setText("Scintigraphy");
            BoutonTomographie.setText("Tomography");
            BoutonAjouter.setText("Add");      
            
        }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterRadiologie(new DialogueBD(),new Utilisateur("Cot","Harry",true,"Français", 1,1111,"Y"),"3").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAjouter;
    private javax.swing.JRadioButton BoutonEchographie;
    private javax.swing.JRadioButton BoutonIRM;
    private javax.swing.JRadioButton BoutonRadiographie;
    private javax.swing.JRadioButton BoutonScanner;
    private javax.swing.JRadioButton BoutonScintigraphie;
    private javax.swing.JRadioButton BoutonTomographie;
    private javax.swing.JLabel Commentaire;
    private javax.swing.JLabel Date;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JLabel DemandeExamenRadiologie;
    private javax.swing.JLabel TypeExamen;
    private javax.swing.JTextArea ZoneCommentaire;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
