/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.validerActes;

/**
 *
 * @author emmaa
 */
public class ValiderExamenBiologique extends javax.swing.JFrame {

    /**
     * Creates new form ValiderExamenBiologique
     */
    public ValiderExamenBiologique() {
        initComponents();
        //Pour empêcher le redimensionnement de la fenêtre, on utilise setResizable(false)
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ValiderExamenBiologique = new javax.swing.JLabel();
        TypeExamen = new javax.swing.JLabel();
        TypeExamenBiologique = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        dateExamenBiologique = new javax.swing.JLabel();
        commentaire = new javax.swing.JLabel();
        zoneCommentaire = new javax.swing.JScrollPane();
        ZoneCommentaire = new javax.swing.JTextArea();
        BoutonValiderExamenBiologique = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ValiderExamenBiologique.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ValiderExamenBiologique.setText("Valider l'examen biologique ");

        TypeExamen.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TypeExamen.setText("Type d'examen : ");

        TypeExamenBiologique.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TypeExamenBiologique.setText("TypeExamenBiologique");

        Date.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Date.setText("Date : ");

        dateExamenBiologique.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        dateExamenBiologique.setText("dateExamenBiologique");

        commentaire.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        commentaire.setText("Commentaire : ");

        ZoneCommentaire.setColumns(20);
        ZoneCommentaire.setRows(5);
        zoneCommentaire.setViewportView(ZoneCommentaire);

        BoutonValiderExamenBiologique.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BoutonValiderExamenBiologique.setText("Valider l'examen biologique");
        BoutonValiderExamenBiologique.setActionCommand("Valider ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zoneCommentaire)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValiderExamenBiologique)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TypeExamen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TypeExamenBiologique))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateExamenBiologique))
                            .addComponent(commentaire))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(BoutonValiderExamenBiologique)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ValiderExamenBiologique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeExamen)
                    .addComponent(TypeExamenBiologique))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(dateExamenBiologique))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zoneCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoutonValiderExamenBiologique)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValiderExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValiderExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValiderExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValiderExamenBiologique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValiderExamenBiologique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonValiderExamenBiologique;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel TypeExamen;
    private javax.swing.JLabel TypeExamenBiologique;
    private javax.swing.JLabel ValiderExamenBiologique;
    private javax.swing.JTextArea ZoneCommentaire;
    private javax.swing.JLabel commentaire;
    private javax.swing.JLabel dateExamenBiologique;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane zoneCommentaire;
    // End of variables declaration//GEN-END:variables
}
