/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.validerActes;

import fc.DialogueBD;
import fc.Utilisateur;

import java.sql.ResultSet;

/**
 * @author emmaa
 */
public class ValiderRadiologie extends javax.swing.JFrame {

    /**
     * Creates new form ValiderRadiologie
     */
    private DialogueBD dialogueBD;
    private Utilisateur utilisateur;
    private String idSejour;

    public ValiderRadiologie(Utilisateur utilisateur, String idActe, DialogueBD dialogueBD) {
        initComponents();
        this.utilisateur = utilisateur;
        this.dialogueBD = dialogueBD;
        //Pour empêcher le redimensionnement de la fenêtre, on utilise setResizable(false)
        setResizable(false);
        remplirRadiologie(idActe);
        //Pour basculer l'interface en anglais lorsqu'elle la langue "English" est sélectionnée
        changerLangue(this.utilisateur.getLangue());
    }

    private void remplirRadiologie(String idActe) {
        //On récupère les informations de la radiologie à partir de la base de données
        String requete = "SELECT * FROM Acte WHERE idActe = " + idActe;
        ResultSet resultSet = dialogueBD.requete(requete);
        try {
            if (resultSet.next()) {
                typeExamenValeur.setText(resultSet.getString("nom"));
                dateRadiologie.setText(resultSet.getString("dateRealisationActe").substring(0, 10));

                texteCommentaire.setText(resultSet.getString("commentaire"));
                if(resultSet.getString("commentaire") == null){
                    texteCommentaire.setText("Aucun commentaire");
                }
                texteResultat.setText(resultSet.getString("resultat"));
                if(resultSet.getString("resultat") == null){
                    texteResultat.setText("Aucun résultat");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfos = new javax.swing.JPanel();
        ValiderRadiologie = new javax.swing.JLabel();
        TypeExamen = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        typeExamenValeur = new javax.swing.JLabel();
        dateRadiologie = new javax.swing.JLabel();
        panelCommentaire = new javax.swing.JPanel();
        zoneCommentaire = new javax.swing.JScrollPane();
        texteCommentaire = new javax.swing.JTextArea();
        commentaire = new javax.swing.JLabel();
        panelResultat = new javax.swing.JPanel();
        labelResultat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texteResultat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(236, 242, 254));

        panelInfos.setBackground(new java.awt.Color(236, 242, 254));

        ValiderRadiologie.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ValiderRadiologie.setText("Imagerie");

        TypeExamen.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TypeExamen.setText("Type d'imagerie :");
        TypeExamen.setToolTipText("");

        Date.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Date.setText("Date : ");

        typeExamenValeur.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        typeExamenValeur.setText("TypeExamen");

        dateRadiologie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        dateRadiologie.setText("dateRadiologie");

        javax.swing.GroupLayout panelInfosLayout = new javax.swing.GroupLayout(panelInfos);
        panelInfos.setLayout(panelInfosLayout);
        panelInfosLayout.setHorizontalGroup(
            panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValiderRadiologie)
                    .addGroup(panelInfosLayout.createSequentialGroup()
                        .addComponent(TypeExamen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeExamenValeur))
                    .addGroup(panelInfosLayout.createSequentialGroup()
                        .addComponent(Date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateRadiologie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfosLayout.setVerticalGroup(
            panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ValiderRadiologie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeExamen)
                    .addComponent(typeExamenValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(dateRadiologie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelInfos, java.awt.BorderLayout.NORTH);

        panelCommentaire.setBackground(new java.awt.Color(236, 242, 254));

        texteCommentaire.setEditable(false);
        texteCommentaire.setColumns(20);
        texteCommentaire.setRows(5);
        zoneCommentaire.setViewportView(texteCommentaire);

        commentaire.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        commentaire.setText("Commentaire");

        javax.swing.GroupLayout panelCommentaireLayout = new javax.swing.GroupLayout(panelCommentaire);
        panelCommentaire.setLayout(panelCommentaireLayout);
        panelCommentaireLayout.setHorizontalGroup(
            panelCommentaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommentaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCommentaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zoneCommentaire, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(panelCommentaireLayout.createSequentialGroup()
                        .addComponent(commentaire)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCommentaireLayout.setVerticalGroup(
            panelCommentaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommentaireLayout.createSequentialGroup()
                .addComponent(commentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zoneCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panelCommentaire, java.awt.BorderLayout.CENTER);

        panelResultat.setBackground(new java.awt.Color(236, 242, 254));

        labelResultat.setText("Resultat :");

        texteResultat.setEditable(false);
        texteResultat.setColumns(20);
        texteResultat.setRows(5);
        jScrollPane1.setViewportView(texteResultat);

        javax.swing.GroupLayout panelResultatLayout = new javax.swing.GroupLayout(panelResultat);
        panelResultat.setLayout(panelResultatLayout);
        panelResultatLayout.setHorizontalGroup(
            panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(panelResultatLayout.createSequentialGroup()
                        .addComponent(labelResultat)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelResultatLayout.setVerticalGroup(
            panelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultatLayout.createSequentialGroup()
                .addComponent(labelResultat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelResultat, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changerLangue(String langue) {
        //Si la langue selectionnée lors la connexion est l'anglais, alors l'interface s'affiche en anglais
        //On remplace chaque composant par son équivalent anglais
        if (langue.equals("English")) {
            ValiderRadiologie.setText("Imagery");
            labelResultat.setText("Result :");
            TypeExamen.setText("Type of Imagery");
            texteCommentaire.setText("Comment");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ValiderRadiologie().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel TypeExamen;
    private javax.swing.JLabel ValiderRadiologie;
    private javax.swing.JLabel commentaire;
    private javax.swing.JLabel dateRadiologie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelResultat;
    private javax.swing.JPanel panelCommentaire;
    private javax.swing.JPanel panelInfos;
    private javax.swing.JPanel panelResultat;
    private javax.swing.JTextArea texteCommentaire;
    private javax.swing.JTextArea texteResultat;
    private javax.swing.JLabel typeExamenValeur;
    private javax.swing.JScrollPane zoneCommentaire;
    // End of variables declaration//GEN-END:variables
}
