/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.validerActes;

import fc.DialogueBD;
import fc.Utilisateur;

/**
 *
 * @author emmaa
 */
public class ValiderRadiologie extends javax.swing.JFrame {

    /**
     * Creates new form ValiderRadiologie
     */
    private DialogueBD dialogueBD;
    private Utilisateur utilisateur;
    private String idSejour;
    
    public ValiderRadiologie() {
        initComponents();
        //Pour empêcher le redimensionnement de la fenêtre, on utilise setResizable(false)
        setResizable(false);
        //Pour basculer l'interface en anglais lorsqu'elle la langue "English" est sélectionnée
        changerLangue(this.utilisateur.getLangue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ValiderRadiologie = new javax.swing.JLabel();
        TypeExamen = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        commentaire = new javax.swing.JLabel();
        zoneCommentaire = new javax.swing.JScrollPane();
        JTextArea = new javax.swing.JTextArea();
        boutonValiderRadiologie = new javax.swing.JButton();
        typeExamenValeur = new javax.swing.JLabel();
        dateRadiologie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 242, 254));

        ValiderRadiologie.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ValiderRadiologie.setText("Valider la radiologie");

        TypeExamen.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TypeExamen.setText("Type d'examen(s) :");
        TypeExamen.setToolTipText("");

        Date.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Date.setText("Date : ");

        commentaire.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        commentaire.setText("Commentaire");

        JTextArea.setColumns(20);
        JTextArea.setRows(5);
        zoneCommentaire.setViewportView(JTextArea);

        boutonValiderRadiologie.setBackground(new java.awt.Color(4, 66, 114));
        boutonValiderRadiologie.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        boutonValiderRadiologie.setForeground(new java.awt.Color(255, 255, 255));
        boutonValiderRadiologie.setText("Valider la radiologie");

        typeExamenValeur.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        typeExamenValeur.setText("TypeExamen");

        dateRadiologie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        dateRadiologie.setText("dateRadiologie");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zoneCommentaire)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValiderRadiologie)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TypeExamen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeExamenValeur))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateRadiologie))
                            .addComponent(commentaire))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(boutonValiderRadiologie)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ValiderRadiologie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeExamen)
                    .addComponent(typeExamenValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(dateRadiologie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentaire)
                .addGap(11, 11, 11)
                .addComponent(zoneCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonValiderRadiologie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void changerLangue(String langue) {
        //Si la langue selectionnée lors la connexion est l'anglais, alors l'interface s'affiche en anglais
        //On remplace chaque composant par son équivalent anglais
        if (langue.equals("English")) {
            ValiderRadiologie.setText("Validate radiology");
            boutonValiderRadiologie.setText("Validate");
            TypeExamen.setText("Type of medical examination");
            JTextArea.setText("Comment");
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValiderRadiologie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValiderRadiologie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JTextArea JTextArea;
    private javax.swing.JLabel TypeExamen;
    private javax.swing.JLabel ValiderRadiologie;
    private javax.swing.JButton boutonValiderRadiologie;
    private javax.swing.JLabel commentaire;
    private javax.swing.JLabel dateRadiologie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel typeExamenValeur;
    private javax.swing.JScrollPane zoneCommentaire;
    // End of variables declaration//GEN-END:variables
}
